import 'package:trip_tailor/widgets/app_bar/custom_app_bar.dart';import 'package:trip_tailor/widgets/app_bar/appbar_leading_image.dart';import 'package:trip_tailor/widgets/app_bar/appbar_subtitle_two.dart';import 'package:trip_tailor/widgets/app_bar/appbar_trailing_image.dart';import 'package:calendar_date_picker2/calendar_date_picker2.dart';import 'package:trip_tailor/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:trip_tailor/core/app_export.dart';import 'controller/attaraction_select_date_controller.dart';class AttaractionSelectDateScreen extends GetWidget<AttaractionSelectDateController> {const AttaractionSelectDateScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [_buildTopBar(), Container(height: 708.v, width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 42.v), child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [_buildDay(), SizedBox(height: 29.v), _buildCalendar(), SizedBox(height: 23.v), _buildCalendar1(), SizedBox(height: 26.v), Padding(padding: EdgeInsets.only(left: 13.h, right: 60.h), child: Row(children: [Text("lbl_25".tr, style: CustomTextStyles.titleSmallGray900_2), Spacer(flex: 19), Text("lbl_26".tr, style: CustomTextStyles.titleSmallGray900_2), Spacer(flex: 20), Text("lbl_27".tr, style: CustomTextStyles.titleSmallGray900_2), Spacer(flex: 20), Text("lbl_28".tr, style: CustomTextStyles.titleSmallGray900_2), Spacer(flex: 20), Text("lbl_29".tr, style: CustomTextStyles.titleSmallGray900_2), Spacer(flex: 20), Text("lbl_30".tr, style: CustomTextStyles.titleSmallGray900_2)]))]))), _buildBottomBar()]))])))); } 
/// Section Widget
Widget _buildTopBar() { return Container(decoration: AppDecoration.fillPrimary, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, top: 16.v, bottom: 16.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleTwo(text: "lbl_attractions".tr), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgRewindOnprimarycontainer, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 16.v))], styleType: Style.bgOutline_2), SizedBox(height: 12.v), Padding(padding: EdgeInsets.only(left: 24.h, right: 70.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgMapPinAmber200, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(bottom: 2.v)), Padding(padding: EdgeInsets.only(left: 8.h, top: 5.v, bottom: 2.v), child: Text("lbl_los_angeles".tr, style: CustomTextStyles.bodyMediumOnPrimaryContainer)), Spacer(), SizedBox(height: 24.v, child: VerticalDivider(width: 1.h, thickness: 1.v, color: appTheme.cyanA10001)), CustomImageView(imagePath: ImageConstant.imgCalendarAmber200, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(left: 15.h, bottom: 2.v)), Padding(padding: EdgeInsets.only(left: 8.h, top: 5.v, bottom: 1.v), child: Text("lbl_26_31_aug".tr, style: CustomTextStyles.titleSmallOnPrimaryContainer_1))])), SizedBox(height: 12.v)])); } 
/// Section Widget
Widget _buildDay() { return Container(padding: EdgeInsets.symmetric(vertical: 15.v), decoration: AppDecoration.fillGray10001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.spaceAround, children: [Text("lbl_s".tr, style: CustomTextStyles.titleSmallBold), Text("lbl_m".tr, style: CustomTextStyles.titleSmallBold), Text("lbl_t".tr, style: CustomTextStyles.titleSmallBold), Text("lbl_w".tr, style: CustomTextStyles.titleSmallBold), Text("lbl_t".tr, style: CustomTextStyles.titleSmallBold), Text("lbl_f".tr, style: CustomTextStyles.titleSmallBold), Text("lbl_s".tr, style: CustomTextStyles.titleSmallBold)])); } 
/// Section Widget
Widget _buildCalendar() { return Obx(() => SizedBox(height: 238.v, width: 327.h, child: CalendarDatePicker2(config: CalendarDatePicker2Config(calendarType: CalendarDatePicker2Type.range, rangeBidirectional: true, firstDate: DateTime(DateTime.now().year - 5), lastDate: DateTime(DateTime.now().year + 5), selectedDayHighlightColor: Color(0XFFE8FCFF), firstDayOfWeek: 0, selectedDayTextStyle: TextStyle(color: Color(0XFF111827), fontFamily: 'Urbanist', fontWeight: FontWeight.w500), dayTextStyle: TextStyle(color: appTheme.gray600, fontFamily: 'Urbanist', fontWeight: FontWeight.w500), dayBorderRadius: BorderRadius.horizontal(left: Radius.circular(10.h))), value: controller.selectedDatesFromCalendar1.value, onValueChanged: (dates) {controller.selectedDatesFromCalendar1.value = dates;}))); } 
/// Section Widget
Widget _buildCalendar1() { return Obx(() => SizedBox(height: 183.v, width: 313.h, child: CalendarDatePicker2(config: CalendarDatePicker2Config(calendarType: CalendarDatePicker2Type.single, firstDate: DateTime(DateTime.now().year - 5), lastDate: DateTime(DateTime.now().year + 5), firstDayOfWeek: 0, dayTextStyle: TextStyle(color: appTheme.gray900, fontFamily: 'Urbanist', fontWeight: FontWeight.w500)), value: controller.selectedDatesFromCalendar2.value, onValueChanged: (dates) {controller.selectedDatesFromCalendar2.value = dates;}))); } 
/// Section Widget
Widget _buildBottomBar() { return Align(alignment: Alignment.bottomCenter, child: Container(padding: EdgeInsets.symmetric(horizontal: 24.h), decoration: AppDecoration.outlineGrayF, child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 12.v), CustomElevatedButton(text: "lbl_confirm".tr)]))); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
