import 'package:trip_tailor/widgets/app_bar/custom_app_bar.dart';import 'package:trip_tailor/widgets/app_bar/appbar_leading_image.dart';import 'package:trip_tailor/widgets/app_bar/appbar_trailing_image.dart';import 'package:trip_tailor/presentation/hotel_detail_overview_page/hotel_detail_overview_page.dart';import 'package:trip_tailor/presentation/hotel_detail_coupons_page/hotel_detail_coupons_page.dart';import 'package:trip_tailor/presentation/hotel_detail_review_page/hotel_detail_review_page.dart';import 'package:flutter/material.dart';import 'package:trip_tailor/core/app_export.dart';import 'controller/hotel_detail_overview_tab_container_controller.dart';class HotelDetailOverviewTabContainerScreen extends GetWidget<HotelDetailOverviewTabContainerController> {const HotelDetailOverviewTabContainerScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(height: 768.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [_buildContent(), Container(margin: EdgeInsets.only(top: 172.v), height: 640.v, child: TabBarView(controller: controller.tabviewController, children: [HotelDetailOverviewPage(), HotelDetailOverviewPage(), HotelDetailCouponsPage(), HotelDetailCouponsPage(), HotelDetailReviewPage()]))])))); } 
/// Section Widget
Widget _buildContent() { return Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.only(top: 44.v), child: Column(mainAxisSize: MainAxisSize.min, children: [CustomAppBar(height: 64.v, leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowLeft();}), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgTwitter, margin: EdgeInsets.only(left: 24.h, top: 20.v, right: 20.h)), AppbarTrailingImage(imagePath: ImageConstant.imgHeartOnprimarycontainer, margin: EdgeInsets.only(left: 16.h, top: 20.v, right: 44.h))], styleType: Style.bgOutline_1), SizedBox(height: 24.v), Container(height: 40.v, width: 351.h, child: TabBar(controller: controller.tabviewController, isScrollable: true, labelColor: theme.colorScheme.primary, labelStyle: TextStyle(fontSize: 14.fSize, fontFamily: 'Urbanist', fontWeight: FontWeight.w700), unselectedLabelColor: appTheme.gray600, unselectedLabelStyle: TextStyle(fontSize: 14.fSize, fontFamily: 'Urbanist', fontWeight: FontWeight.w500), indicator: BoxDecoration(color: appTheme.lightBlue50, borderRadius: BorderRadius.circular(10.h)), tabs: [Tab(child: Text("lbl_overview".tr)), Tab(child: Text("lbl_amentities".tr)), Tab(child: Text("lbl_coupons".tr)), Tab(child: Text("lbl_location".tr)), Tab(child: Text("lbl_reviews".tr))]))]))); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
