import 'package:trip_tailor/widgets/app_bar/custom_app_bar.dart';import 'package:trip_tailor/widgets/app_bar/appbar_leading_image.dart';import 'package:trip_tailor/widgets/app_bar/appbar_subtitle.dart';import 'package:trip_tailor/widgets/custom_text_form_field.dart';import 'package:trip_tailor/widgets/custom_drop_down.dart';import 'package:trip_tailor/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:trip_tailor/core/app_export.dart';import 'controller/hotel_booking_step_1_add_special_request_controller.dart';class HotelBookingStep1AddSpecialRequestScreen extends GetWidget<HotelBookingStep1AddSpecialRequestController> {const HotelBookingStep1AddSpecialRequestScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 15.v), child: Column(children: [_buildQuote(), SizedBox(height: 8.v), _buildItem(), _buildItem1(), _buildItem2(), SizedBox(height: 27.v), _buildTime(), SizedBox(height: 24.v), _buildInput(), SizedBox(height: 5.v)])), bottomNavigationBar: _buildDone())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgCloseGray900, margin: EdgeInsets.only(left: 24.h, top: 15.v, bottom: 16.v), onTap: () {onTapClose();}), centerTitle: true, title: AppbarSubtitle(text: "lbl_special_request2".tr)); } 
/// Section Widget
Widget _buildQuote() { return Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 12.v), decoration: AppDecoration.fillGray10001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 5.v), SizedBox(width: 295.h, child: Text("msg_have_any_requests".tr, maxLines: 3, overflow: TextOverflow.ellipsis, style: theme.textTheme.labelLarge!.copyWith(height: 1.70)))])); } 
/// Section Widget
Widget _buildItem() { return CustomTextFormField(controller: controller.itemController, hintText: "msg_non_smoking_room2".tr, prefix: Container(margin: EdgeInsets.fromLTRB(3.h, 22.v, 19.h, 22.v), child: CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 13.adaptSize, width: 13.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 58.v), contentPadding: EdgeInsets.only(top: 19.v, right: 30.h, bottom: 19.v), borderDecoration: TextFormFieldStyleHelper.outlineGray1); } 
/// Section Widget
Widget _buildItem1() { return Container(padding: EdgeInsets.only(top: 16.v, bottom: 15.v), decoration: AppDecoration.outlineGray2004, child: Row(children: [CustomImageView(imagePath: ImageConstant.imgThumbsupGray200, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 2.v)), Padding(padding: EdgeInsets.only(left: 16.h, top: 4.v), child: Text("lbl_connecting_room".tr, style: CustomTextStyles.titleMediumMedium))])); } 
/// Section Widget
Widget _buildItem2() { return CustomTextFormField(controller: controller.itemController1, hintText: "lbl_high_floor_room".tr, prefix: Container(margin: EdgeInsets.fromLTRB(3.h, 22.v, 19.h, 22.v), child: CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 13.adaptSize, width: 13.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 58.v), contentPadding: EdgeInsets.only(top: 19.v, right: 30.h, bottom: 19.v), borderDecoration: TextFormFieldStyleHelper.outlineGray1); } 
/// Section Widget
Widget _buildTime() { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Padding(padding: EdgeInsets.only(right: 8.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_checkin_time".tr, style: CustomTextStyles.titleMediumGray600), SizedBox(height: 14.v), CustomDropDown(width: 155.h, icon: Container(margin: EdgeInsets.fromLTRB(30.h, 18.v, 16.h, 18.v), child: CustomImageView(imagePath: ImageConstant.imgArrowDownBlueGray30001, height: 20.adaptSize, width: 20.adaptSize)), hintText: "lbl_09_00_pm".tr, items: controller.hotelBookingStep1AddSpecialRequestModelObj.value.dropdownItemList!.value)]))), Expanded(child: Padding(padding: EdgeInsets.only(left: 8.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_checkout_time".tr, style: CustomTextStyles.titleMediumGray600), SizedBox(height: 14.v), CustomDropDown(width: 155.h, icon: Container(margin: EdgeInsets.fromLTRB(30.h, 18.v, 16.h, 18.v), child: CustomImageView(imagePath: ImageConstant.imgArrowDownBlueGray30001, height: 20.adaptSize, width: 20.adaptSize)), hintText: "lbl_12_00_pm".tr, items: controller.hotelBookingStep1AddSpecialRequestModelObj.value.dropdownItemList1!.value)])))]); } 
/// Section Widget
Widget _buildInput() { return CustomTextFormField(controller: controller.inputController, hintText: "lbl_others".tr, hintStyle: theme.textTheme.bodyLarge!, textInputAction: TextInputAction.done, maxLines: 6, borderDecoration: TextFormFieldStyleHelper.outlineBlueGray); } 
/// Section Widget
Widget _buildDone() { return CustomElevatedButton(text: "lbl_done".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 42.v)); } 

/// Navigates to the previous screen.
onTapClose() { Get.back(); } 
 }
