import 'package:trip_tailor/widgets/custom_drop_down.dart';import 'widgets/list22_item_widget.dart';import 'models/list22_item_model.dart';import 'package:trip_tailor/widgets/custom_outlined_button.dart';import 'package:trip_tailor/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:trip_tailor/core/app_export.dart';import 'controller/wishlist_filter_controller.dart';
// ignore_for_file: must_be_immutable
class WishlistFilterBottomsheet extends StatelessWidget {WishlistFilterBottomsheet(this.controller, {Key? key}) : super(key: key);

WishlistFilterController controller;

@override Widget build(BuildContext context) { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 16.v), decoration: AppDecoration.fillOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.customBorderTL35), child: Column(mainAxisSize: MainAxisSize.min, children: [Container(height: 8.v, width: 40.h, decoration: BoxDecoration(color: appTheme.gray100, borderRadius: BorderRadius.circular(4.h))), SizedBox(height: 18.v), _buildFrame(), SizedBox(height: 18.v), Divider(), SizedBox(height: 26.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_products".tr, style: CustomTextStyles.titleMediumGray600)), SizedBox(height: 18.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 18.v, 16.h, 18.v), child: CustomImageView(imagePath: ImageConstant.imgArrowDownBlueGray30001, height: 20.adaptSize, width: 20.adaptSize)), hintText: "lbl_plane".tr, hintStyle: theme.textTheme.titleMedium!, items: controller.wishlistFilterModelObj.value.dropdownItemList!.value, prefix: Container(margin: EdgeInsets.fromLTRB(24.h, 20.v, 20.h, 20.v), child: CustomImageView(imagePath: ImageConstant.imgAirplaneOnprimarycontainer, height: 16.adaptSize, width: 16.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 56.v), contentPadding: EdgeInsets.symmetric(vertical: 18.v), borderDecoration: DropDownStyleHelper.outlineBlueGrayTL16), SizedBox(height: 27.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_added_time".tr, style: CustomTextStyles.titleMediumGray600)), SizedBox(height: 20.v), _buildList(), SizedBox(height: 46.v), _buildHeader(), SizedBox(height: 26.v)])); } 
/// Section Widget
Widget _buildFrame() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_filter".tr, style: CustomTextStyles.titleMedium18_1), CustomImageView(imagePath: ImageConstant.imgCloseGray600, height: 20.adaptSize, width: 20.adaptSize, onTap: () {onTapImgClose();})]); } 
/// Section Widget
Widget _buildList() { return Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 16.v);}, itemCount: controller.wishlistFilterModelObj.value.list22ItemList.value.length, itemBuilder: (context, index) {List22ItemModel model = controller.wishlistFilterModelObj.value.list22ItemList.value[index]; return List22ItemWidget(model);})); } 
/// Section Widget
Widget _buildHeader() { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: CustomOutlinedButton(height: 48.v, text: "lbl_reset".tr, margin: EdgeInsets.only(right: 8.h), buttonStyle: CustomButtonStyles.outlineGrayTL12, buttonTextStyle: CustomTextStyles.titleSmallGray90001)), Expanded(child: CustomElevatedButton(height: 48.v, text: "lbl_apply".tr, margin: EdgeInsets.only(left: 8.h), buttonStyle: CustomButtonStyles.fillPrimaryTL12, buttonTextStyle: CustomTextStyles.titleSmallOnPrimaryContainer))]); } 

/// Navigates to the previous screen.
onTapImgClose() { Get.back(); } 
 }
