import 'package:dotted_border/dotted_border.dart';import 'package:flutter/material.dart';import 'package:trip_tailor/core/app_export.dart';import 'controller/flight_booking_price_detail_controller.dart';
// ignore_for_file: must_be_immutable
class FlightBookingPriceDetailBottomsheet extends StatelessWidget {FlightBookingPriceDetailBottomsheet(this.controller, {Key? key}) : super(key: key);

FlightBookingPriceDetailController controller;

@override Widget build(BuildContext context) { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 16.v), decoration: AppDecoration.fillOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.customBorderTL35), child: Column(mainAxisSize: MainAxisSize.min, children: [Container(height: 8.v, width: 40.h, decoration: BoxDecoration(color: appTheme.gray100, borderRadius: BorderRadius.circular(4.h))), SizedBox(height: 18.v), _buildFrame(), SizedBox(height: 18.v), Divider(), SizedBox(height: 22.v), _buildCard(), SizedBox(height: 15.v), _buildPrice(), SizedBox(height: 25.v)])); } 
/// Section Widget
Widget _buildFrame() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_price_detail".tr, style: CustomTextStyles.titleMedium18_1), CustomImageView(imagePath: ImageConstant.imgCloseGray600, height: 20.adaptSize, width: 20.adaptSize, onTap: () {onTapImgClose();})]); } 
/// Section Widget
Widget _buildCard() { return Container(padding: EdgeInsets.all(15.h), decoration: AppDecoration.outlineBluegray1001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [CustomImageView(imagePath: ImageConstant.imgQatarAirwaysSvg, height: 20.adaptSize, width: 20.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h, top: 3.v), child: Text("lbl_qatar_airways".tr, style: CustomTextStyles.labelLargeGray900_1))]), SizedBox(height: 12.v), Row(children: [Padding(padding: EdgeInsets.symmetric(vertical: 3.v), child: Text("lbl_sin".tr, style: CustomTextStyles.titleSmallGray900_2)), CustomImageView(imagePath: ImageConstant.imgTelevisionBlueGray100, height: 6.v, margin: EdgeInsets.only(left: 16.h, top: 9.v, bottom: 9.v)), CustomImageView(imagePath: ImageConstant.imgAirplaneBlueGray30001, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(left: 4.h)), CustomImageView(imagePath: ImageConstant.imgSettingsBlueGray1006x92, height: 6.v, margin: EdgeInsets.only(left: 4.h, top: 9.v, bottom: 9.v)), Padding(padding: EdgeInsets.only(left: 16.h, top: 3.v, bottom: 3.v), child: Text("lbl_lhr".tr, style: CustomTextStyles.titleSmallGray900_2))])])); } 
/// Section Widget
Widget _buildPrice() { return Container(padding: EdgeInsets.all(19.h), decoration: AppDecoration.outlineBluegray100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [DottedBorder(color: appTheme.blueGray100, padding: EdgeInsets.only(left: 1.h, top: 1.v, right: 1.h, bottom: 1.v), strokeWidth: 1.h, dashPattern: [4, 4], child: Container(padding: EdgeInsets.only(top: 2.v, bottom: 1.v), decoration: AppDecoration.outlineBluegray1004, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_price".tr, style: CustomTextStyles.labelLargeGray900), SizedBox(height: 8.v), Text("lbl_1_adult".tr, style: theme.textTheme.labelLarge)]), Padding(padding: EdgeInsets.only(top: 23.v), child: Text("lbl_744_00".tr, style: CustomTextStyles.labelLargeGray900))]), SizedBox(height: 16.v), Text("lbl_add_ons".tr, style: CustomTextStyles.labelLargeGray900), SizedBox(height: 9.v), _buildAmount(title: "msg_free_protections".tr, title1: "lbl_free".tr), SizedBox(height: 14.v)]))), SizedBox(height: 16.v), Container(padding: EdgeInsets.only(top: 2.v, bottom: 1.v), decoration: AppDecoration.outlineGray2001, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_price_deductions".tr, style: CustomTextStyles.labelLargeGray900), SizedBox(height: 9.v), Text("lbl_discount".tr, style: theme.textTheme.labelLarge)]), Padding(padding: EdgeInsets.only(top: 24.v), child: Text("lbl_0_00".tr, style: CustomTextStyles.labelLargeGray900))]), SizedBox(height: 16.v), Text("lbl_other_fees".tr, style: CustomTextStyles.labelLargeGray900), SizedBox(height: 9.v), _buildAmount(title: "lbl_tax".tr, title1: "lbl_included".tr), SizedBox(height: 16.v)])), SizedBox(height: 19.v), _buildAmount(title: "lbl_total_price".tr, title1: "lbl_744_00".tr)])); } 
/// Common widget
Widget _buildAmount({required String title, required String title1, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(title, style: theme.textTheme.labelLarge!.copyWith(color: appTheme.gray600)), Text(title1, style: CustomTextStyles.labelLargeGray900.copyWith(color: appTheme.gray900))]); } 

/// Navigates to the previous screen.
onTapImgClose() { Get.back(); } 
 }
