import 'package:trip_tailor/widgets/app_bar/custom_app_bar.dart';import 'package:trip_tailor/widgets/app_bar/appbar_leading_image.dart';import 'package:trip_tailor/widgets/app_bar/appbar_subtitle.dart';import 'package:staggered_grid_view_flutter/widgets/staggered_grid_view.dart';import 'package:staggered_grid_view_flutter/widgets/staggered_tile.dart';import 'widgets/img3_item_widget.dart';import 'models/img3_item_model.dart';import 'package:flutter/material.dart';import 'package:trip_tailor/core/app_export.dart';import 'controller/hotel_select_room_detail_photos_controller.dart';class HotelSelectRoomDetailPhotosScreen extends GetWidget<HotelSelectRoomDetailPhotosController> {const HotelSelectRoomDetailPhotosScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 16.v), child: SizedBox(height: 788.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.center, child: SizedBox(height: 788.v, width: 327.h, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgImg150x156, height: 150.v, radius: BorderRadius.circular(12.h), alignment: Alignment.bottomLeft), Align(alignment: Alignment.center, child: SizedBox(height: 788.v, width: 327.h, child: Stack(alignment: Alignment.topCenter, children: [CustomImageView(imagePath: ImageConstant.imgImg220x155, width: 155.h, radius: BorderRadius.circular(12.h), alignment: Alignment.bottomRight), _buildImg()])))]))), Align(alignment: Alignment.bottomCenter, child: Container(height: 98.v, width: double.maxFinite, margin: EdgeInsets.only(bottom: 96.v), decoration: BoxDecoration(gradient: LinearGradient(begin: Alignment(0.5, 1.11), end: Alignment(0.5, 0.08), colors: [theme.colorScheme.onPrimaryContainer.withOpacity(1), theme.colorScheme.onPrimaryContainer.withOpacity(0)]))))])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowRight, margin: EdgeInsets.only(left: 24.h, top: 16.v, bottom: 16.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitle(text: "lbl_guest_room".tr)); } 
/// Section Widget
Widget _buildImg() { return Obx(() => StaggeredGridView.countBuilder(shrinkWrap: true, primary: false, crossAxisCount: 4, crossAxisSpacing: 16.h, mainAxisSpacing: 16.h, staggeredTileBuilder: (index) {return StaggeredTile.fit(2);}, itemCount: controller.hotelSelectRoomDetailPhotosModelObj.value.img3ItemList.value.length, itemBuilder: (context, index) {Img3ItemModel model = controller.hotelSelectRoomDetailPhotosModelObj.value.img3ItemList.value[index]; return Img3ItemWidget(model);})); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
