name: trip_tailor
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.6
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  google_sign_in: ^5.0.7
  flutter_login_facebook: ^1.6.2
  pin_code_fields: ^8.0.1
  country_pickers: ^2.0.0
  smooth_page_indicator: ^1.1.0
  sms_autofill: ^2.3.0
  calendar_date_picker2: ^0.5.3
  carousel_slider: ^4.2.1
  readmore: ^2.2.0
  google_maps_flutter: ^2.5.0
  staggered_grid_view_flutter: ^0.0.4
  dotted_border: ^2.1.0
  grouped_list: ^5.1.2
  intl: ^0.18.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Urbanist
      fonts: 
        - asset: assets/fonts/UrbanistBold.ttf
          weight: 700
        - asset: assets/fonts/UrbanistMedium.ttf
          weight: 500
        - asset: assets/fonts/UrbanistRegular.ttf
          weight: 400
        - asset: assets/fonts/UrbanistRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/UrbanistRomanBold.ttf
          weight: 700
    - family: Plus Jakarta Sans
      fonts: 
        - asset: assets/fonts/PlusJakartaSansBold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSansMedium.ttf
          weight: 500
    - family: SF Pro Display
      fonts: 
        - asset: assets/fonts/SFProDisplayBold.ttf
          weight: 700
