import 'package:trip_tailor/widgets/custom_icon_button.dart';import 'package:trip_tailor/widgets/custom_checkbox_button.dart';import 'package:trip_tailor/widgets/custom_drop_down.dart';import 'widgets/list21_item_widget.dart';import 'models/list21_item_model.dart';import 'package:trip_tailor/widgets/custom_outlined_button.dart';import 'package:trip_tailor/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:trip_tailor/core/app_export.dart';import 'controller/my_booking_sort_filter_controller.dart';
// ignore_for_file: must_be_immutable
class MyBookingSortFilterBottomsheet extends StatelessWidget {MyBookingSortFilterBottomsheet(this.controller, {Key? key}) : super(key: key);

MyBookingSortFilterController controller;

@override Widget build(BuildContext context) { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 16.v), decoration: AppDecoration.fillOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.customBorderTL35), child: Column(mainAxisSize: MainAxisSize.min, children: [Container(height: 8.v, width: 40.h, decoration: BoxDecoration(color: appTheme.gray100, borderRadius: BorderRadius.circular(4.h))), SizedBox(height: 18.v), _buildFrame(), SizedBox(height: 18.v), Divider(), SizedBox(height: 28.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_sort_by".tr, style: CustomTextStyles.titleMediumGray600)), SizedBox(height: 19.v), _buildItem(), SizedBox(height: 16.v), _buildPurchasedate(), SizedBox(height: 29.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_products".tr, style: CustomTextStyles.titleMediumGray600)), SizedBox(height: 18.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 18.v, 16.h, 18.v), child: CustomImageView(imagePath: ImageConstant.imgArrowDownBlueGray30001, height: 20.adaptSize, width: 20.adaptSize)), hintText: "lbl_plane".tr, hintStyle: theme.textTheme.titleMedium!, items: controller.myBookingSortFilterModelObj.value.dropdownItemList!.value, prefix: Container(margin: EdgeInsets.fromLTRB(24.h, 20.v, 20.h, 20.v), child: CustomImageView(imagePath: ImageConstant.imgAirplaneOnprimarycontainer, height: 16.adaptSize, width: 16.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 56.v), contentPadding: EdgeInsets.symmetric(vertical: 18.v), borderDecoration: DropDownStyleHelper.outlineBlueGrayTL16), SizedBox(height: 27.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_order_date".tr, style: CustomTextStyles.titleMediumGray600)), SizedBox(height: 20.v), _buildList(), SizedBox(height: 38.v), _buildHeader(), SizedBox(height: 26.v)])); } 
/// Section Widget
Widget _buildFrame() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_sort_filter".tr, style: CustomTextStyles.titleMedium18_1), CustomImageView(imagePath: ImageConstant.imgCloseGray600, height: 20.adaptSize, width: 20.adaptSize, onTap: () {onTapImgClose();})]); } 
/// Section Widget
Widget _buildItem() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.symmetric(vertical: 1.v), child: Text("lbl_ordered_date".tr, style: CustomTextStyles.titleSmallGray900)), CustomIconButton(height: 20.adaptSize, width: 20.adaptSize, padding: EdgeInsets.all(3.h), decoration: IconButtonStyleHelper.fillPrimary, child: CustomImageView(imagePath: ImageConstant.imgArrowLeft))]); } 
/// Section Widget
Widget _buildPurchasedate() { return Obx(() => CustomCheckboxButton(width: 327.h, text: "lbl_purchase_date".tr, value: controller.purchasedate.value, padding: EdgeInsets.symmetric(vertical: 1.v), textStyle: CustomTextStyles.titleSmallGray900, isRightCheck: true, onChange: (value) {controller.purchasedate.value = value;})); } 
/// Section Widget
Widget _buildList() { return Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 16.v);}, itemCount: controller.myBookingSortFilterModelObj.value.list21ItemList.value.length, itemBuilder: (context, index) {List21ItemModel model = controller.myBookingSortFilterModelObj.value.list21ItemList.value[index]; return List21ItemWidget(model);})); } 
/// Section Widget
Widget _buildHeader() { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: CustomOutlinedButton(height: 48.v, text: "lbl_reset".tr, margin: EdgeInsets.only(right: 8.h), buttonStyle: CustomButtonStyles.outlineGrayTL12, buttonTextStyle: CustomTextStyles.titleSmallGray90001)), Expanded(child: CustomElevatedButton(height: 48.v, text: "lbl_apply".tr, margin: EdgeInsets.only(left: 8.h), buttonStyle: CustomButtonStyles.fillPrimaryTL12, buttonTextStyle: CustomTextStyles.titleSmallOnPrimaryContainer))]); } 

/// Navigates to the previous screen.
onTapImgClose() { Get.back(); } 
 }
