import 'package:trip_tailor/widgets/app_bar/custom_app_bar.dart';import 'package:trip_tailor/widgets/app_bar/appbar_leading_image.dart';import 'package:trip_tailor/widgets/app_bar/appbar_subtitle.dart';import 'package:trip_tailor/widgets/custom_text_form_field.dart';import 'package:trip_tailor/widgets/custom_drop_down.dart';import 'package:trip_tailor/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:trip_tailor/core/app_export.dart';import 'controller/link_account_payment_method_add_new_controller.dart';class LinkAccountPaymentMethodAddNewScreen extends GetWidget<LinkAccountPaymentMethodAddNewController> {const LinkAccountPaymentMethodAddNewScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 19.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_card_name".tr, style: CustomTextStyles.titleMediumMedium), SizedBox(height: 14.v), CustomTextFormField(controller: controller.nameController, hintText: "msg_francene_vandyne".tr, borderDecoration: TextFormFieldStyleHelper.outlineBlueGray), SizedBox(height: 27.v), Text("lbl_card_number".tr, style: CustomTextStyles.titleMediumMedium), SizedBox(height: 14.v), _buildInput(), SizedBox(height: 27.v), _buildInputDate(), SizedBox(height: 29.v), Text("lbl_country".tr, style: CustomTextStyles.titleMediumMedium), SizedBox(height: 12.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 18.v, 16.h, 18.v), child: CustomImageView(imagePath: ImageConstant.imgArrowDownBlueGray30001, height: 20.adaptSize, width: 20.adaptSize)), hintText: "lbl_united_states".tr, items: controller.linkAccountPaymentMethodAddNewModelObj.value.dropdownItemList!.value, prefix: Container(margin: EdgeInsets.fromLTRB(16.h, 16.v, 12.h, 16.v), child: CustomImageView(imagePath: ImageConstant.imgUnitedStates, height: 24.adaptSize, width: 24.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 56.v), contentPadding: EdgeInsets.symmetric(vertical: 18.v), borderDecoration: DropDownStyleHelper.outlineBlueGrayTL16), Spacer(), SizedBox(height: 66.v), CustomElevatedButton(text: "lbl_save_card".tr, buttonStyle: CustomButtonStyles.outlineGrayTL16)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowRight, margin: EdgeInsets.only(left: 24.h, top: 16.v, bottom: 16.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitle(text: "lbl_add_card".tr)); } 
/// Section Widget
Widget _buildInput() { return Container(padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 16.v), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Row(children: [Text("lbl_12456".tr, style: CustomTextStyles.bodyLargeGray900), Padding(padding: EdgeInsets.only(left: 2.h), child: SizedBox(height: 20.v, child: VerticalDivider(width: 1.h, thickness: 1.v, color: theme.colorScheme.primary))), Spacer(), CustomImageView(imagePath: ImageConstant.imgThumbsUpBlueGray3000120x20, height: 20.adaptSize, width: 20.adaptSize)])); } 
/// Section Widget
Widget _buildInputDate() { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Padding(padding: EdgeInsets.only(top: 2.v, right: 8.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_exp_date".tr, style: CustomTextStyles.titleMediumMedium), SizedBox(height: 12.v), CustomTextFormField(width: 155.h, controller: controller.dateController, hintText: "lbl_mm_yy".tr, hintStyle: CustomTextStyles.bodyLargeBluegray30001, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 18.v, 16.h, 18.v), child: CustomImageView(imagePath: ImageConstant.imgProfileBlueGray3000120x20, height: 20.adaptSize, width: 20.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 56.v), contentPadding: EdgeInsets.only(left: 16.h, top: 18.v, bottom: 18.v), borderDecoration: TextFormFieldStyleHelper.outlineBlueGray)]))), Expanded(child: Padding(padding: EdgeInsets.only(left: 8.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_cvv".tr, style: CustomTextStyles.titleMediumMedium), SizedBox(height: 14.v), CustomTextFormField(width: 155.h, controller: controller.cvvController, hintText: "lbl_123".tr, hintStyle: CustomTextStyles.bodyLargeBluegray30001, textInputAction: TextInputAction.done, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 18.v, 16.h, 18.v), child: CustomImageView(imagePath: ImageConstant.imgProfileBlueGray3000120x20, height: 20.adaptSize, width: 20.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 56.v), contentPadding: EdgeInsets.only(left: 16.h, top: 18.v, bottom: 18.v), borderDecoration: TextFormFieldStyleHelper.outlineBlueGray)])))]); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
