import 'package:carousel_slider/carousel_slider.dart';import 'widgets/businessclass_item_widget.dart';import 'models/businessclass_item_model.dart';import 'package:smooth_page_indicator/smooth_page_indicator.dart';import 'package:trip_tailor/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:trip_tailor/core/app_export.dart';import 'controller/train_select_seat_number_controller.dart';class TrainSelectSeatNumberScreen extends GetWidget<TrainSelectSeatNumberController> {const TrainSelectSeatNumberScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.primary, body: Container(width: double.maxFinite, padding: EdgeInsets.only(left: 24.h, top: 64.v, right: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 24.adaptSize, width: 24.adaptSize, onTap: () {onTapImgArrowLeft();}), Padding(padding: EdgeInsets.only(left: 92.h), child: Text("lbl_select_seat".tr, style: CustomTextStyles.titleMediumOnPrimaryContainer18))]), SizedBox(height: 34.v), _buildDetail(), SizedBox(height: 34.v), SizedBox(height: 494.v, width: 327.h, child: Stack(alignment: Alignment.bottomRight, children: [_buildBusinessClass(), Align(alignment: Alignment.bottomRight, child: Obx(() => Container(height: 6.v, margin: EdgeInsets.only(right: 113.h, bottom: 24.v), child: AnimatedSmoothIndicator(activeIndex: controller.sliderIndex.value, count: controller.trainSelectSeatNumberModelObj.value.businessclassItemList.value.length, axisDirection: Axis.horizontal, effect: ScrollingDotsEffect(spacing: 6, activeDotColor: appTheme.gray900, dotColor: appTheme.gray200, dotHeight: 6.v, dotWidth: 6.h)))))])), SizedBox(height: 5.v)])), bottomNavigationBar: _buildBottomBar())); } 
/// Section Widget
Widget _buildDetail() { return Row(children: [Container(height: 12.adaptSize, width: 12.adaptSize, decoration: BoxDecoration(color: appTheme.amber200, borderRadius: BorderRadius.circular(4.h))), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("lbl_available".tr, style: CustomTextStyles.labelLargeOnPrimaryContainer)), Spacer(flex: 50), Container(height: 12.adaptSize, width: 12.adaptSize, decoration: BoxDecoration(borderRadius: BorderRadius.circular(4.h), border: Border.all(color: appTheme.amber200, width: 1.h))), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("lbl_selected".tr, style: CustomTextStyles.labelLargeOnPrimaryContainer)), Spacer(flex: 50), Container(height: 12.adaptSize, width: 12.adaptSize, decoration: BoxDecoration(color: appTheme.lightBlueA200, borderRadius: BorderRadius.circular(4.h))), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("lbl_unavailable".tr, style: CustomTextStyles.labelLargeOnPrimaryContainer))]); } 
/// Section Widget
Widget _buildBusinessClass() { return Obx(() => CarouselSlider.builder(options: CarouselOptions(height: 494.v, initialPage: 0, autoPlay: true, viewportFraction: 1.0, enableInfiniteScroll: false, scrollDirection: Axis.horizontal, onPageChanged: (index, reason) {controller.sliderIndex.value = index;}), itemCount: controller.trainSelectSeatNumberModelObj.value.businessclassItemList.value.length, itemBuilder: (context, index, realIndex) {BusinessclassItemModel model = controller.trainSelectSeatNumberModelObj.value.businessclassItemList.value[index]; return BusinessclassItemWidget(model);})); } 
/// Section Widget
Widget _buildDone() { return CustomElevatedButton(width: 159.h, text: "lbl_done".tr); } 
/// Section Widget
Widget _buildBottomBar() { return Container(margin: EdgeInsets.symmetric(horizontal: 24.h), decoration: AppDecoration.outlineGrayF.copyWith(borderRadius: BorderRadiusStyle.customBorderTL24), child: Container(decoration: AppDecoration.outlineGrayF.copyWith(borderRadius: BorderRadiusStyle.customBorderTL24), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.symmetric(vertical: 5.v), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [Text("lbl_65_00".tr, style: theme.textTheme.titleLarge), CustomImageView(imagePath: ImageConstant.imgArrowDownBlueGray30001, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(left: 4.h, top: 4.v, bottom: 4.v))]), Padding(padding: EdgeInsets.only(top: 6.v), child: Row(children: [Text("lbl_5a".tr, style: theme.textTheme.labelLarge), Container(height: 4.adaptSize, width: 4.adaptSize, margin: EdgeInsets.only(left: 6.h, top: 5.v, bottom: 5.v), decoration: BoxDecoration(color: appTheme.blueGray100, borderRadius: BorderRadius.circular(2.h))), Padding(padding: EdgeInsets.only(left: 6.h), child: Text("lbl_business_class".tr, style: theme.textTheme.labelLarge))]))])), _buildDone()]))); } 

/// Navigates to the previous screen.
onTapImgArrowLeft() { Get.back(); } 
 }
