import 'package:trip_tailor/widgets/custom_icon_button.dart';import 'package:trip_tailor/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:trip_tailor/core/app_export.dart';import 'controller/train_select_passenger_controller.dart';
// ignore_for_file: must_be_immutable
class TrainSelectPassengerBottomsheet extends StatelessWidget {TrainSelectPassengerBottomsheet(this.controller, {Key? key}) : super(key: key);

TrainSelectPassengerController controller;

@override Widget build(BuildContext context) { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 16.v), decoration: AppDecoration.fillOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.customBorderTL35), child: Column(mainAxisSize: MainAxisSize.min, children: [Container(height: 8.v, width: 40.h, decoration: BoxDecoration(color: appTheme.gray100, borderRadius: BorderRadius.circular(4.h))), SizedBox(height: 19.v), _buildFrame(), SizedBox(height: 16.v), Divider(), SizedBox(height: 29.v), _buildItem(), SizedBox(height: 28.v), _buildItem1(), SizedBox(height: 26.v), _buildItem2(), SizedBox(height: 29.v), CustomElevatedButton(text: "lbl_confirm".tr), SizedBox(height: 26.v)])); } 
/// Section Widget
Widget _buildFrame() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text("msg_select_passenger".tr, style: CustomTextStyles.titleMedium18_1)), CustomImageView(imagePath: ImageConstant.imgCloseGray600, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(bottom: 3.v), onTap: () {onTapImgClose();})]); } 
/// Section Widget
Widget _buildItem() { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_adults".tr, style: theme.textTheme.titleMedium), SizedBox(height: 8.v), Text("msg_adults_13_or_above".tr, style: theme.textTheme.labelLarge)]), Spacer(), Padding(padding: EdgeInsets.only(top: 9.v, bottom: 10.v), child: CustomIconButton(height: 24.adaptSize, width: 24.adaptSize, padding: EdgeInsets.all(4.h), decoration: IconButtonStyleHelper.outlineBlueGray, child: CustomImageView(imagePath: ImageConstant.imgMinus))), Padding(padding: EdgeInsets.only(left: 20.h, top: 11.v, bottom: 10.v), child: Text("lbl_1".tr, style: CustomTextStyles.titleMedium18)), Padding(padding: EdgeInsets.only(left: 21.h, top: 9.v, bottom: 10.v), child: CustomIconButton(height: 24.adaptSize, width: 24.adaptSize, padding: EdgeInsets.all(4.h), decoration: IconButtonStyleHelper.outlineBlueGray, child: CustomImageView(imagePath: ImageConstant.imgPlus)))]); } 
/// Section Widget
Widget _buildItem1() { return Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_childreen".tr, style: theme.textTheme.titleMedium), SizedBox(height: 10.v), Text("lbl_ages_2_12".tr, style: theme.textTheme.labelLarge)]), Spacer(), Padding(padding: EdgeInsets.only(top: 9.v, bottom: 11.v), child: CustomIconButton(height: 24.adaptSize, width: 24.adaptSize, padding: EdgeInsets.all(4.h), decoration: IconButtonStyleHelper.outlineBlueGray, child: CustomImageView(imagePath: ImageConstant.imgMinusBlueGray30001))), Padding(padding: EdgeInsets.only(left: 17.h, top: 11.v, bottom: 11.v), child: Text("lbl_0".tr, style: CustomTextStyles.titleMediumGray60018)), Padding(padding: EdgeInsets.only(left: 17.h, top: 9.v, bottom: 11.v), child: CustomIconButton(height: 24.adaptSize, width: 24.adaptSize, padding: EdgeInsets.all(4.h), decoration: IconButtonStyleHelper.outlineBlueGray, child: CustomImageView(imagePath: ImageConstant.imgPlus)))]); } 
/// Section Widget
Widget _buildItem2() { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_infants".tr, style: theme.textTheme.titleMedium), SizedBox(height: 9.v), Text("lbl_under_2".tr, style: theme.textTheme.labelLarge)]), Spacer(), Padding(padding: EdgeInsets.only(top: 9.v, bottom: 10.v), child: CustomIconButton(height: 24.adaptSize, width: 24.adaptSize, padding: EdgeInsets.all(4.h), decoration: IconButtonStyleHelper.outlineBlueGray, child: CustomImageView(imagePath: ImageConstant.imgMinusBlueGray30001))), Padding(padding: EdgeInsets.only(left: 17.h, top: 11.v, bottom: 10.v), child: Text("lbl_0".tr, style: CustomTextStyles.titleMediumGray60018)), Padding(padding: EdgeInsets.only(left: 17.h, top: 9.v, bottom: 10.v), child: CustomIconButton(height: 24.adaptSize, width: 24.adaptSize, padding: EdgeInsets.all(4.h), decoration: IconButtonStyleHelper.outlineBlueGray, child: CustomImageView(imagePath: ImageConstant.imgPlus)))]); } 

/// Navigates to the previous screen.
onTapImgClose() { Get.back(); } 
 }
