import 'package:trip_tailor/widgets/app_bar/custom_app_bar.dart';import 'package:trip_tailor/widgets/app_bar/appbar_leading_image.dart';import 'package:trip_tailor/widgets/app_bar/appbar_subtitle_one.dart';import 'package:trip_tailor/widgets/app_bar/appbar_trailing_image.dart';import 'widgets/list16_item_widget.dart';import 'models/list16_item_model.dart';import 'package:trip_tailor/widgets/custom_icon_button.dart';import 'package:trip_tailor/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:trip_tailor/core/app_export.dart';import 'controller/train_select_travel_extra_protection_controller.dart';class TrainSelectTravelExtraProtectionScreen extends GetWidget<TrainSelectTravelExtraProtectionController> {const TrainSelectTravelExtraProtectionScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: Container(height: SizeUtils.height, width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 38.v), child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.center, child: Column(mainAxisSize: MainAxisSize.min, children: [_buildAppBar(), SizedBox(height: 29.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Text("msg_extra_protections".tr, style: theme.textTheme.titleMedium))), SizedBox(height: 16.v), _buildList(), SizedBox(height: 24.v), _buildGuarantee()])), _buildBottomBar()])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 64.v, leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleOne(text: "lbl_booking".tr), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgDotsVerticalOnprimarycontainer, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 20.v))], styleType: Style.bgOutline_1); } 
/// Section Widget
Widget _buildList() { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 16.v);}, itemCount: controller.trainSelectTravelExtraProtectionModelObj.value.list16ItemList.value.length, itemBuilder: (context, index) {List16ItemModel model = controller.trainSelectTravelExtraProtectionModelObj.value.list16ItemList.value[index]; return List16ItemWidget(model);}))); } 
/// Section Widget
Widget _buildGuarantee() { return Container(margin: EdgeInsets.symmetric(horizontal: 24.h), padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 10.v), decoration: AppDecoration.fillGray10001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Row(mainAxisAlignment: MainAxisAlignment.center, mainAxisSize: MainAxisSize.min, children: [Padding(padding: EdgeInsets.symmetric(vertical: 3.v), child: CustomIconButton(height: 48.adaptSize, width: 48.adaptSize, padding: EdgeInsets.all(12.h), decoration: IconButtonStyleHelper.fillOnPrimaryContainer, child: CustomImageView(imagePath: ImageConstant.imgCloseBlueGray80001))), Expanded(child: Padding(padding: EdgeInsets.only(left: 12.h, top: 3.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_lowest_price_guarentee".tr, style: CustomTextStyles.labelLargeGray900), SizedBox(height: 3.v), SizedBox(width: 242.h, child: Text("msg_get_compensated".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.labelMedium!.copyWith(height: 1.60)))])))])); } 
/// Section Widget
Widget _buildBottomBar() { return Align(alignment: Alignment.bottomCenter, child: Container(width: double.maxFinite, margin: EdgeInsets.only(top: 668.v), padding: EdgeInsets.symmetric(horizontal: 24.h), decoration: AppDecoration.outlineGrayF, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(top: 17.v, bottom: 4.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [Text("lbl_38_00".tr, style: theme.textTheme.titleLarge), CustomImageView(imagePath: ImageConstant.imgArrowDownBlueGray30001, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(left: 4.h, top: 4.v, bottom: 4.v))]), SizedBox(height: 7.v), RichText(text: TextSpan(children: [TextSpan(text: "lbl_get".tr, style: CustomTextStyles.labelLargeff6b7280), TextSpan(text: "lbl_1_000_points".tr, style: CustomTextStyles.labelLargee816d4e9)]), textAlign: TextAlign.left)])), CustomElevatedButton(width: 159.h, text: "lbl_continue".tr, margin: EdgeInsets.only(top: 12.v))]))); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
