import 'package:trip_tailor/widgets/app_bar/custom_app_bar.dart';import 'package:trip_tailor/widgets/app_bar/appbar_leading_image.dart';import 'package:trip_tailor/widgets/app_bar/appbar_subtitle_one.dart';import 'package:trip_tailor/widgets/app_bar/appbar_trailing_image.dart';import 'package:calendar_date_picker2/calendar_date_picker2.dart';import 'package:trip_tailor/widgets/custom_icon_button.dart';import 'package:trip_tailor/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:trip_tailor/core/app_export.dart';import 'controller/attaraction_order_details_controller.dart';class AttaractionOrderDetailsScreen extends GetWidget<AttaractionOrderDetailsController> {const AttaractionOrderDetailsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 42.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 25.v), _buildRoom(), SizedBox(height: 27.v), Text("lbl_selected_dates".tr, style: theme.textTheme.titleMedium), SizedBox(height: 18.v), _buildCalendar(), SizedBox(height: 29.v), Text("lbl_ticket_quantity".tr, style: theme.textTheme.titleMedium), SizedBox(height: 17.v), _buildBookNow()])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 64.v, leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleOne(text: "lbl_booking".tr), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgDotsVerticalOnprimarycontainer, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 20.v))], styleType: Style.bgOutline_1); } 
/// Section Widget
Widget _buildRoom() { return Container(padding: EdgeInsets.symmetric(vertical: 15.v), decoration: AppDecoration.outlineBluegray100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Row(mainAxisAlignment: MainAxisAlignment.spaceEvenly, children: [CustomImageView(imagePath: ImageConstant.imgImg41, height: 72.adaptSize, width: 72.adaptSize, radius: BorderRadius.circular(10.h)), Padding(padding: EdgeInsets.only(top: 6.v, bottom: 3.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_2_day_1_park_disneyland2".tr, style: CustomTextStyles.titleSmallGray900), SizedBox(height: 6.v), Text("msg_california_united".tr, style: theme.textTheme.labelLarge), SizedBox(height: 8.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgArrowDownBlueGray30001, height: 16.adaptSize, width: 16.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("msg_free_cancellation".tr, style: theme.textTheme.labelLarge))])]))])); } 
/// Section Widget
Widget _buildCalendar() { return Obx(() => SizedBox(height: 308.v, width: 327.h, child: CalendarDatePicker2(config: CalendarDatePicker2Config(calendarType: CalendarDatePicker2Type.single, firstDate: DateTime(DateTime.now().year - 5), lastDate: DateTime(DateTime.now().year + 5), selectedDayHighlightColor: Color(0XE816D4E9), firstDayOfWeek: 0, weekdayLabelTextStyle: TextStyle(color: appTheme.gray600, fontFamily: 'Urbanist', fontWeight: FontWeight.w700), selectedDayTextStyle: TextStyle(color: Color(0XFFFFFFFF), fontFamily: 'Urbanist', fontWeight: FontWeight.w700), dayTextStyle: TextStyle(color: appTheme.blueGray30001, fontFamily: 'Urbanist', fontWeight: FontWeight.w500), weekdayLabels: ["S", "M", "T", "W", "T", "F", "S"], dayBorderRadius: BorderRadius.circular(8.h)), value: controller.selectedDatesFromCalendar1.value, onValueChanged: (dates) {controller.selectedDatesFromCalendar1.value = dates;}))); } 
/// Section Widget
Widget _buildBookNow() { return SizedBox(height: 94.v, width: 327.h, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topCenter, child: Container(margin: EdgeInsets.only(bottom: 21.v), padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 12.v), decoration: AppDecoration.outlineBluegray100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_travellers".tr, style: theme.textTheme.labelLarge), SizedBox(height: 10.v), Text("lbl_255_00".tr, style: theme.textTheme.titleMedium)]), Spacer(), Padding(padding: EdgeInsets.symmetric(vertical: 11.v), child: CustomIconButton(height: 22.adaptSize, width: 22.adaptSize, padding: EdgeInsets.all(4.h), decoration: IconButtonStyleHelper.outlineBlueGray, child: CustomImageView(imagePath: ImageConstant.imgMinusBlueGray30001))), Padding(padding: EdgeInsets.only(left: 16.h, top: 12.v, bottom: 11.v), child: Text("lbl_1".tr, style: CustomTextStyles.titleMedium18)), Padding(padding: EdgeInsets.only(left: 17.h, top: 11.v, bottom: 11.v), child: CustomIconButton(height: 22.adaptSize, width: 22.adaptSize, padding: EdgeInsets.all(4.h), decoration: IconButtonStyleHelper.outlineBlueGray, child: CustomImageView(imagePath: ImageConstant.imgPlus)))]))), CustomElevatedButton(width: 327.h, text: "lbl_book_now".tr, buttonStyle: CustomButtonStyles.outlineBlue, alignment: Alignment.bottomCenter)])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
