import 'package:trip_tailor/widgets/custom_drop_down.dart';import 'package:trip_tailor/widgets/custom_text_form_field.dart';import 'package:trip_tailor/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:trip_tailor/core/app_export.dart';import 'controller/train_select_traveler_details_controller.dart';class TrainSelectTravelerDetailsScreen extends GetWidget<TrainSelectTravelerDetailsController> {const TrainSelectTravelerDetailsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: Container(width: double.maxFinite, padding: EdgeInsets.only(left: 24.h, top: 64.v, right: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(right: 89.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgCloseGray900, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(bottom: 1.v), onTap: () {onTapImgClose();}), Padding(padding: EdgeInsets.only(left: 66.h, top: 3.v), child: Text("msg_passenger_details".tr, style: CustomTextStyles.titleMedium18_1))])), SizedBox(height: 33.v), Text("lbl_title".tr, style: CustomTextStyles.titleMediumGray600), SizedBox(height: 14.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 18.v, 16.h, 18.v), child: CustomImageView(imagePath: ImageConstant.imgArrowDownBlueGray30001, height: 20.adaptSize, width: 20.adaptSize)), hintText: "lbl_mrs".tr, items: controller.trainSelectTravelerDetailsModelObj.value.dropdownItemList!.value), SizedBox(height: 19.v), Text("lbl_full_name2".tr, style: CustomTextStyles.titleMediumGray600), SizedBox(height: 14.v), CustomTextFormField(controller: controller.fullNameController, hintText: "msg_francene_vandyne".tr, borderDecoration: TextFormFieldStyleHelper.outlineBlueGray), SizedBox(height: 21.v), Text("lbl_id_type".tr, style: CustomTextStyles.titleMediumGray600), SizedBox(height: 12.v), CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 18.v, 16.h, 18.v), child: CustomImageView(imagePath: ImageConstant.imgArrowDownBlueGray30001, height: 20.adaptSize, width: 20.adaptSize)), hintText: "lbl_passport".tr, items: controller.trainSelectTravelerDetailsModelObj.value.dropdownItemList1!.value), SizedBox(height: 19.v), Text("lbl_id_number".tr, style: CustomTextStyles.titleMediumGray600), SizedBox(height: 14.v), CustomTextFormField(controller: controller.zipcodeController, hintText: "lbl_786554".tr, textInputAction: TextInputAction.done), SizedBox(height: 5.v)])), bottomNavigationBar: _buildDone())); } 
/// Section Widget
Widget _buildDone() { return CustomElevatedButton(text: "lbl_done".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 42.v)); } 

/// Navigates to the previous screen.
onTapImgClose() { Get.back(); } 
 }
