import 'package:trip_tailor/widgets/custom_icon_button.dart';import 'package:trip_tailor/widgets/custom_outlined_button.dart';import 'widgets/list13_item_widget.dart';import 'models/list13_item_model.dart';import 'widgets/thumbsup1_item_widget.dart';import 'models/thumbsup1_item_model.dart';import 'package:trip_tailor/widgets/app_bar/custom_app_bar.dart';import 'package:trip_tailor/widgets/app_bar/appbar_leading_image.dart';import 'package:trip_tailor/widgets/app_bar/appbar_subtitle.dart';import 'package:trip_tailor/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:trip_tailor/core/app_export.dart';import 'controller/flight_filter_scroll_down_controller.dart';class FlightFilterScrollDownScreen extends GetWidget<FlightFilterScrollDownController> {const FlightFilterScrollDownScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(height: SizeUtils.height, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.center, child: SizedBox(height: 804.v, width: double.maxFinite, child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [_buildAirlines(), _buildTransit(), SizedBox(height: 27.v), Text("msg_departure_in_london".tr, style: CustomTextStyles.titleMedium18), SizedBox(height: 15.v), _buildThumbsUp()]))), _buildAppBar()]))), _buildBottomBar()])))); } 
/// Section Widget
Widget _buildAirlines() { return Container(decoration: AppDecoration.outlineBluegray1003, child: Column(children: [Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(right: 7.h), child: _buildItem(title: "lbl_emirates".tr)), Padding(padding: EdgeInsets.symmetric(horizontal: 7.h), child: _buildItem(title: "lbl_thai_airways".tr)), Padding(padding: EdgeInsets.only(left: 7.h), child: _buildItem(title: "lbl_finnair".tr))]), SizedBox(height: 16.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(right: 7.h), child: _buildItem1(title: "lbl_scandinavian".tr)), Padding(padding: EdgeInsets.symmetric(horizontal: 7.h), child: _buildItem1(title: "lbl_british_airways".tr)), Padding(padding: EdgeInsets.only(left: 7.h), child: _buildItem1(title: "lbl_qatar_airways".tr))]), SizedBox(height: 16.v), CustomOutlinedButton(height: 48.v, text: "lbl_load_more".tr, buttonStyle: CustomButtonStyles.outlinePrimary, buttonTextStyle: CustomTextStyles.titleSmallPrimaryBold), SizedBox(height: 24.v)])); } 
/// Section Widget
Widget _buildTransit() { return Container(padding: EdgeInsets.only(top: 25.v, bottom: 24.v), decoration: AppDecoration.outlineGray2001, child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), Text("msg_travel_and_baggage".tr, style: CustomTextStyles.titleMedium18), SizedBox(height: 18.v), Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 21.v);}, itemCount: controller.flightFilterScrollDownModelObj.value.list13ItemList.value.length, itemBuilder: (context, index) {List13ItemModel model = controller.flightFilterScrollDownModelObj.value.list13ItemList.value[index]; return List13ItemWidget(model);}))])); } 
/// Section Widget
Widget _buildThumbsUp() { return Obx(() => GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 111.v, crossAxisCount: 2, mainAxisSpacing: 16.h, crossAxisSpacing: 16.h), physics: NeverScrollableScrollPhysics(), itemCount: controller.flightFilterScrollDownModelObj.value.thumbsup1ItemList.value.length, itemBuilder: (context, index) {Thumbsup1ItemModel model = controller.flightFilterScrollDownModelObj.value.thumbsup1ItemList.value[index]; return Thumbsup1ItemWidget(model);})); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 64.v, leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgCloseGray600, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v), onTap: () {onTapClose();}), centerTitle: true, title: AppbarSubtitle(text: "lbl_filters".tr), styleType: Style.bgOutline); } 
/// Section Widget
Widget _buildBottomBar() { return Align(alignment: Alignment.bottomCenter, child: Container(margin: EdgeInsets.only(left: 6.h, top: 734.v, bottom: 10.v), decoration: AppDecoration.outlineGrayF, child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.end, children: [Expanded(child: CustomOutlinedButton(text: "lbl_reset".tr, margin: EdgeInsets.only(top: 12.v, right: 8.h), buttonStyle: CustomButtonStyles.outlineGray, buttonTextStyle: CustomTextStyles.titleMediumGray90001)), Expanded(child: CustomElevatedButton(text: "lbl_apply".tr, margin: EdgeInsets.only(left: 8.h, top: 12.v)))]))); } 
/// Common widget
Widget _buildItem({required String title}) { return Expanded(child: SizedBox(width: double.maxFinite, child: Container(padding: EdgeInsets.symmetric(horizontal: 15.h), decoration: AppDecoration.outlineBluegray100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgIcon14x48, height: 14.v), SizedBox(height: 11.v), Text(title, style: CustomTextStyles.labelMediumGray900.copyWith(color: appTheme.gray900)), SizedBox(height: 16.v)])))); } 
/// Common widget
Widget _buildItem1({required String title}) { return Expanded(child: SizedBox(width: double.maxFinite, child: Container(padding: EdgeInsets.symmetric(horizontal: 11.h, vertical: 15.v), decoration: AppDecoration.outlineBluegray100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Column(mainAxisSize: MainAxisSize.min, children: [CustomIconButton(height: 48.adaptSize, width: 48.adaptSize, padding: EdgeInsets.all(7.h), decoration: IconButtonStyleHelper.fillGray, child: CustomImageView(imagePath: ImageConstant.imgBritishAirways)), SizedBox(height: 11.v), Text(title, style: CustomTextStyles.labelMediumGray900.copyWith(color: appTheme.gray900))])))); } 

/// Navigates to the previous screen.
onTapClose() { Get.back(); } 
 }
