import 'package:trip_tailor/widgets/app_bar/custom_app_bar.dart';import 'package:trip_tailor/widgets/app_bar/appbar_leading_image.dart';import 'package:trip_tailor/widgets/app_bar/appbar_subtitle.dart';import 'package:trip_tailor/widgets/custom_switch.dart';import 'package:trip_tailor/widgets/custom_icon_button.dart';import 'package:flutter/material.dart';import 'package:trip_tailor/core/app_export.dart';import 'controller/push_notifications_controller.dart';class PushNotificationsScreen extends GetWidget<PushNotificationsController> {const PushNotificationsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 4.v), child: SizedBox(height: 782.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildNotificationItem(), _buildNotificationItem1(), _buildNotificationItem2(), _buildNotificationItem3(), _buildNotificationItem4(), _buildNotificationItem5(), _buildNotificationItem6()]))), Align(alignment: Alignment.bottomCenter, child: Container(height: 98.v, width: double.maxFinite, margin: EdgeInsets.only(bottom: 78.v), decoration: BoxDecoration(gradient: LinearGradient(begin: Alignment(0.5, 1.11), end: Alignment(0.5, 0.08), colors: [theme.colorScheme.onPrimaryContainer.withOpacity(1), theme.colorScheme.onPrimaryContainer.withOpacity(0)]))))])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowRight, margin: EdgeInsets.only(left: 24.h, top: 16.v, bottom: 16.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitle(text: "msg_push_notification".tr)); } 
/// Section Widget
Widget _buildNotificationItem() { return Container(padding: EdgeInsets.symmetric(vertical: 12.v), decoration: AppDecoration.outlineBluegray1003, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 6.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("msg_allow_notification".tr, style: theme.textTheme.titleMedium), Obx(() => CustomSwitch(value: controller.isSelectedSwitch.value, onChange: (value) {controller.isSelectedSwitch.value = value;}))]), SizedBox(height: 12.v), Container(width: 300.h, margin: EdgeInsets.only(right: 26.h), child: Text("msg_receive_notification".tr, maxLines: 3, overflow: TextOverflow.ellipsis, style: theme.textTheme.labelLarge!.copyWith(height: 1.70)))])); } 
/// Section Widget
Widget _buildNotificationItem1() { return Container(padding: EdgeInsets.symmetric(vertical: 12.v), decoration: AppDecoration.outlineBluegray1003, child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Expanded(child: Padding(padding: EdgeInsets.only(top: 6.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_account_activities".tr, style: theme.textTheme.titleMedium), SizedBox(height: 13.v), SizedBox(width: 279.h, child: Text("msg_receive_reports".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.labelLarge!.copyWith(height: 1.70)))]))), Container(height: 20.v, width: 34.h, margin: EdgeInsets.only(left: 13.h, top: 6.v, bottom: 54.v), decoration: AppDecoration.fillGray200.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: CustomIconButton(height: 20.adaptSize, width: 20.adaptSize, padding: EdgeInsets.all(4.h), decoration: IconButtonStyleHelper.outlineGrayTL101, alignment: Alignment.centerLeft, child: CustomImageView(imagePath: ImageConstant.imgCloseBlueGray30001)))])); } 
/// Section Widget
Widget _buildNotificationItem2() { return Container(padding: EdgeInsets.only(top: 13.v, bottom: 12.v), decoration: AppDecoration.outlineBluegray1003, child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Expanded(child: Padding(padding: EdgeInsets.only(top: 5.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_price_alerts".tr, style: theme.textTheme.titleMedium), SizedBox(height: 12.v), SizedBox(width: 290.h, child: Text("msg_you_ll_get_alerted".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.labelLarge!.copyWith(height: 1.70)))]))), Container(height: 20.v, width: 34.h, margin: EdgeInsets.only(left: 3.h, top: 5.v, bottom: 53.v), decoration: AppDecoration.fillGray200.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: CustomIconButton(height: 20.adaptSize, width: 20.adaptSize, padding: EdgeInsets.all(4.h), decoration: IconButtonStyleHelper.outlineGrayTL101, alignment: Alignment.centerLeft, child: CustomImageView(imagePath: ImageConstant.imgCloseBlueGray30001)))])); } 
/// Section Widget
Widget _buildNotificationItem3() { return Container(padding: EdgeInsets.only(top: 13.v, bottom: 12.v), decoration: AppDecoration.outlineBluegray1003, child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Expanded(child: Padding(padding: EdgeInsets.only(top: 7.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_booking_and_payment".tr, style: theme.textTheme.titleMedium), SizedBox(height: 11.v), SizedBox(width: 271.h, child: Text("msg_count_on_us_to_update".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.labelLarge!.copyWith(height: 1.70)))]))), Obx(() => CustomSwitch(margin: EdgeInsets.only(left: 21.h, top: 5.v, bottom: 53.v), value: controller.isSelectedSwitch1.value, onChange: (value) {controller.isSelectedSwitch1.value = value;}))])); } 
/// Section Widget
Widget _buildNotificationItem4() { return Container(padding: EdgeInsets.only(top: 13.v, bottom: 12.v), decoration: AppDecoration.outlineBluegray1003, child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Expanded(child: Padding(padding: EdgeInsets.only(top: 7.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_flight_and_hotel".tr, style: theme.textTheme.titleMedium), SizedBox(height: 10.v), SizedBox(width: 275.h, child: Text("msg_we_ll_remind_you".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.labelLarge!.copyWith(height: 1.70)))]))), Obx(() => CustomSwitch(margin: EdgeInsets.only(left: 17.h, top: 5.v, bottom: 53.v), value: controller.isSelectedSwitch2.value, onChange: (value) {controller.isSelectedSwitch2.value = value;}))])); } 
/// Section Widget
Widget _buildNotificationItem5() { return Container(padding: EdgeInsets.only(top: 13.v, bottom: 12.v), decoration: AppDecoration.outlineBluegray1003, child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Expanded(child: Padding(padding: EdgeInsets.only(top: 7.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_traveline_promos".tr, style: theme.textTheme.titleMedium), SizedBox(height: 10.v), SizedBox(width: 281.h, child: Text("msg_you_ll_love_this".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.labelLarge!.copyWith(height: 1.70)))]))), Obx(() => CustomSwitch(margin: EdgeInsets.only(left: 11.h, top: 5.v, bottom: 53.v), value: controller.isSelectedSwitch3.value, onChange: (value) {controller.isSelectedSwitch3.value = value;}))])); } 
/// Section Widget
Widget _buildNotificationItem6() { return Container(padding: EdgeInsets.only(top: 16.v, bottom: 15.v), decoration: AppDecoration.outlineBluegray1003, child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 3.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("msg_review_activities".tr, style: theme.textTheme.titleMedium), Obx(() => CustomSwitch(value: controller.isSelectedSwitch4.value, onChange: (value) {controller.isSelectedSwitch4.value = value;}))]), SizedBox(height: 10.v), Container(width: 290.h, margin: EdgeInsets.only(right: 37.h), child: Text("msg_receive_notifications".tr, maxLines: null, overflow: TextOverflow.ellipsis, style: theme.textTheme.labelLarge!.copyWith(height: 1.70)))])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
