import 'package:trip_tailor/widgets/app_bar/custom_app_bar.dart';import 'package:trip_tailor/widgets/app_bar/appbar_leading_image.dart';import 'package:trip_tailor/widgets/app_bar/appbar_subtitle_four.dart';import 'package:trip_tailor/widgets/app_bar/appbar_subtitle_ten.dart';import 'package:trip_tailor/widgets/app_bar/appbar_trailing_image.dart';import 'package:trip_tailor/presentation/flight_list_detail_page/flight_list_detail_page.dart';import 'package:trip_tailor/presentation/flight_list_detail_fare_benefit_page/flight_list_detail_fare_benefit_page.dart';import 'package:trip_tailor/presentation/flight_list_detail_refund_info_page/flight_list_detail_refund_info_page.dart';import 'package:trip_tailor/presentation/flight_list_detail_reschedule_info_page/flight_list_detail_reschedule_info_page.dart';import 'package:flutter/material.dart';import 'package:trip_tailor/core/app_export.dart';import 'controller/flight_list_detail_tab_container_controller.dart';class FlightListDetailTabContainerScreen extends GetWidget<FlightListDetailTabContainerController> {const FlightListDetailTabContainerScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [_buildSixtyTwo(), Expanded(child: SizedBox(height: 660.v, child: TabBarView(controller: controller.tabviewController, children: [FlightListDetailPage(), FlightListDetailFareBenefitPage(), FlightListDetailRefundInfoPage(), FlightListDetailRescheduleInfoPage()])))])))); } 
/// Section Widget
Widget _buildSixtyTwo() { return Container(decoration: AppDecoration.fillPrimary, child: Column(children: [SizedBox(height: 59.v), CustomAppBar(height: 37.v, leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, top: 4.v, bottom: 8.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: Column(children: [AppbarSubtitleFour(text: "lbl_qatar_airways".tr, margin: EdgeInsets.symmetric(horizontal: 12.h)), SizedBox(height: 4.v), Row(children: [AppbarSubtitleTen(text: "lbl_sin_lhr".tr, margin: EdgeInsets.only(bottom: 1.v)), Container(height: 4.adaptSize, width: 4.adaptSize, margin: EdgeInsets.only(left: 6.h, top: 5.v, bottom: 6.v), decoration: BoxDecoration(color: appTheme.cyanA100, borderRadius: BorderRadius.circular(2.h))), AppbarSubtitleTen(text: "lbl_economy".tr, margin: EdgeInsets.only(left: 6.h, top: 1.v))])]), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgTwitter, margin: EdgeInsets.fromLTRB(24.h, 4.v, 24.h, 8.v))]), SizedBox(height: 15.v), Container(height: 40.v, width: 322.h, child: TabBar(controller: controller.tabviewController, labelPadding: EdgeInsets.zero, labelColor: appTheme.amber200, labelStyle: TextStyle(fontSize: 12.fSize, fontFamily: 'Urbanist', fontWeight: FontWeight.w700), unselectedLabelColor: appTheme.cyan100, unselectedLabelStyle: TextStyle(fontSize: 12.fSize, fontFamily: 'Urbanist', fontWeight: FontWeight.w500), indicator: BoxDecoration(border: Border(bottom: BorderSide(color: appTheme.amber200, width: 2.h))), tabs: [Tab(child: Text("lbl_flight".tr)), Tab(child: Text("lbl_fare_benefit".tr)), Tab(child: Text("lbl_refund".tr)), Tab(child: Text("lbl_reschedule".tr))]))])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
