import 'package:trip_tailor/widgets/app_bar/custom_app_bar.dart';import 'package:trip_tailor/widgets/app_bar/appbar_leading_image.dart';import 'package:trip_tailor/widgets/app_bar/appbar_subtitle_two.dart';import 'package:trip_tailor/widgets/app_bar/appbar_trailing_image.dart';import 'package:trip_tailor/widgets/custom_elevated_button.dart';import 'widgets/list20_item_widget.dart';import 'models/list20_item_model.dart';import 'package:flutter/material.dart';import 'package:trip_tailor/core/app_export.dart';import 'controller/attaraction_select_location_controller.dart';class AttaractionSelectLocationScreen extends GetWidget<AttaractionSelectLocationController> {const AttaractionSelectLocationScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [_buildTopBar(), Container(padding: EdgeInsets.only(left: 24.h, top: 68.v, right: 24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomElevatedButton(height: 48.v, text: "msg_use_current_location".tr, leftIcon: Container(margin: EdgeInsets.only(right: 12.h), child: CustomImageView(imagePath: ImageConstant.imgSave, height: 20.adaptSize, width: 20.adaptSize)), buttonStyle: CustomButtonStyles.fillGrayTL12, buttonTextStyle: CustomTextStyles.titleSmallPrimaryBold), SizedBox(height: 27.v), _buildList()]))])))); } 
/// Section Widget
Widget _buildTopBar() { return Container(decoration: AppDecoration.fillPrimary, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, top: 16.v, bottom: 16.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleTwo(text: "lbl_attractions".tr), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgRewindOnprimarycontainer, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 16.v))], styleType: Style.bgOutline_2), SizedBox(height: 12.v), Padding(padding: EdgeInsets.only(left: 24.h, right: 60.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgMapPinAmber200, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 2.v)), Padding(padding: EdgeInsets.only(left: 8.h, top: 2.v, bottom: 2.v), child: Text("lbl_los".tr, style: CustomTextStyles.bodyMediumOnPrimaryContainer)), Padding(padding: EdgeInsets.only(left: 2.h), child: SizedBox(height: 24.v, child: VerticalDivider(width: 1.h, thickness: 1.v, color: theme.colorScheme.onPrimaryContainer.withOpacity(1), indent: 2.h, endIndent: 2.h))), Spacer(), SizedBox(height: 24.v, child: VerticalDivider(width: 1.h, thickness: 1.v, color: appTheme.cyanA10001)), CustomImageView(imagePath: ImageConstant.imgCalendarAmber200, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(left: 15.h, top: 2.v, bottom: 2.v)), Padding(padding: EdgeInsets.only(left: 8.h, top: 2.v, bottom: 2.v), child: Text("lbl_select_dates".tr, style: CustomTextStyles.titleSmallCyanA100))])), SizedBox(height: 12.v)])); } 
/// Section Widget
Widget _buildList() { return Padding(padding: EdgeInsets.only(right: 100.h), child: Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 30.v);}, itemCount: controller.attaractionSelectLocationModelObj.value.list20ItemList.value.length, itemBuilder: (context, index) {List20ItemModel model = controller.attaractionSelectLocationModelObj.value.list20ItemList.value[index]; return List20ItemWidget(model);}))); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
