import 'package:trip_tailor/widgets/app_bar/custom_app_bar.dart';import 'package:trip_tailor/widgets/app_bar/appbar_leading_image.dart';import 'package:trip_tailor/widgets/app_bar/appbar_title_searchview.dart';import 'widgets/list5_item_widget.dart';import 'models/list5_item_model.dart';import 'widgets/hiltoncatedral_item_widget.dart';import 'models/hiltoncatedral_item_model.dart';import 'package:flutter/material.dart';import 'package:trip_tailor/core/app_export.dart';import 'controller/search_history_recomendation_controller.dart';class SearchHistoryRecomendationScreen extends GetWidget<SearchHistoryRecomendationController> {const SearchHistoryRecomendationScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 27.v), child: SizedBox(height: 767.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [_buildTitle(), SizedBox(height: 15.v), _buildList(), SizedBox(height: 25.v), Text("lbl_recommendation".tr, style: CustomTextStyles.titleMedium18), SizedBox(height: 17.v), _buildHiltonCatedral()]))), Align(alignment: Alignment.bottomCenter, child: Container(height: 98.v, width: double.maxFinite, margin: EdgeInsets.only(bottom: 91.v), decoration: BoxDecoration(gradient: LinearGradient(begin: Alignment(0.5, 1.11), end: Alignment(0.5, 0.08), colors: [theme.colorScheme.onPrimaryContainer.withOpacity(1), theme.colorScheme.onPrimaryContainer.withOpacity(0)]))))])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowRight, margin: EdgeInsets.only(left: 24.h, top: 16.v, bottom: 16.v), onTap: () {onTapArrowLeft();}), title: AppbarTitleSearchview(margin: EdgeInsets.only(left: 16.h), hintText: "msg_where_are_you_going".tr, controller: controller.searchController)); } 
/// Section Widget
Widget _buildTitle() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text("lbl_history".tr, style: CustomTextStyles.titleMedium18)), Padding(padding: EdgeInsets.only(bottom: 3.v), child: Text("lbl_delete".tr, style: CustomTextStyles.titleMediumPrimaryMedium))]); } 
/// Section Widget
Widget _buildList() { return Padding(padding: EdgeInsets.only(right: 56.h), child: Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 24.v);}, itemCount: controller.searchHistoryRecomendationModelObj.value.list5ItemList.value.length, itemBuilder: (context, index) {List5ItemModel model = controller.searchHistoryRecomendationModelObj.value.list5ItemList.value[index]; return List5ItemWidget(model);}))); } 
/// Section Widget
Widget _buildHiltonCatedral() { return Obx(() => GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 235.v, crossAxisCount: 2, mainAxisSpacing: 20.h, crossAxisSpacing: 20.h), physics: NeverScrollableScrollPhysics(), itemCount: controller.searchHistoryRecomendationModelObj.value.hiltoncatedralItemList.value.length, itemBuilder: (context, index) {HiltoncatedralItemModel model = controller.searchHistoryRecomendationModelObj.value.hiltoncatedralItemList.value[index]; return HiltoncatedralItemWidget(model);})); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
