import 'package:trip_tailor/widgets/app_bar/custom_app_bar.dart';import 'package:trip_tailor/widgets/app_bar/appbar_leading_image.dart';import 'package:trip_tailor/widgets/app_bar/appbar_subtitle.dart';import 'package:trip_tailor/widgets/custom_search_view.dart';import 'package:trip_tailor/widgets/custom_icon_button.dart';import 'package:trip_tailor/presentation/hotel_special_deals_page/hotel_special_deals_page.dart';import 'package:flutter/material.dart';import 'package:trip_tailor/core/app_export.dart';import 'controller/hotel_special_deals_tab_container_controller.dart';class HotelSpecialDealsTabContainerScreen extends GetWidget<HotelSpecialDealsTabContainerController> {const HotelSpecialDealsTabContainerScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 15.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildSearch(), SizedBox(height: 25.v), Padding(padding: EdgeInsets.only(left: 24.h), child: Text("msg_hotels_of_the_week".tr, style: CustomTextStyles.titleMedium18)), SizedBox(height: 17.v), _buildTabview(), SizedBox(height: 539.v, child: TabBarView(controller: controller.tabviewController, children: [HotelSpecialDealsPage(), HotelSpecialDealsPage(), HotelSpecialDealsPage(), HotelSpecialDealsPage()]))]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowRight, margin: EdgeInsets.only(left: 24.h, top: 15.v, bottom: 16.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitle(text: "lbl_special_deals".tr)); } 
/// Section Widget
Widget _buildSearch() { return Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: CustomSearchView(controller: controller.searchController, hintText: "lbl_city_or_area".tr, hintStyle: theme.textTheme.bodyLarge!)), Padding(padding: EdgeInsets.only(left: 12.h), child: CustomIconButton(height: 56.adaptSize, width: 56.adaptSize, padding: EdgeInsets.all(16.h), decoration: IconButtonStyleHelper.outlineGrayTL16, child: CustomImageView(imagePath: ImageConstant.imgTelevision)))]))); } 
/// Section Widget
Widget _buildTabview() { return Container(height: 32.v, width: 351.h, child: TabBar(controller: controller.tabviewController, isScrollable: true, labelColor: theme.colorScheme.primary, labelStyle: TextStyle(fontSize: 12.fSize, fontFamily: 'Urbanist', fontWeight: FontWeight.w700), unselectedLabelColor: appTheme.gray600, unselectedLabelStyle: TextStyle(fontSize: 12.fSize, fontFamily: 'Urbanist', fontWeight: FontWeight.w500), indicator: BoxDecoration(color: appTheme.lightBlue50, borderRadius: BorderRadius.circular(8.h)), tabs: [Tab(child: Text("lbl_los_angeles".tr)), Tab(child: Text("lbl_california".tr)), Tab(child: Text("lbl_manhattan".tr)), Tab(child: Text("lbl_san_francisco".tr))])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
