import 'package:trip_tailor/widgets/app_bar/custom_app_bar.dart';import 'package:trip_tailor/widgets/app_bar/appbar_leading_image.dart';import 'package:trip_tailor/widgets/app_bar/appbar_subtitle.dart';import 'package:trip_tailor/widgets/custom_elevated_button.dart';import 'widgets/list14_item_widget.dart';import 'models/list14_item_model.dart';import 'package:flutter/material.dart';import 'package:trip_tailor/core/app_export.dart';import 'controller/flight_booking_travel_add_on_controller.dart';class FlightBookingTravelAddOnScreen extends GetWidget<FlightBookingTravelAddOnController> {const FlightBookingTravelAddOnScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 19.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildCard(), SizedBox(height: 29.v), Text("msg_add_depart_baggage".tr, style: theme.textTheme.titleMedium), SizedBox(height: 17.v), _buildList()])), bottomNavigationBar: _buildHeader())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgCloseGray900, margin: EdgeInsets.only(left: 24.h, top: 15.v, bottom: 16.v), onTap: () {onTapClose();}), centerTitle: true, title: AppbarSubtitle(text: "lbl_baggage".tr)); } 
/// Section Widget
Widget _buildCard() { return Container(padding: EdgeInsets.all(15.h), decoration: AppDecoration.outlineBluegray1001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [CustomImageView(imagePath: ImageConstant.imgQatarAirwaysSvg, height: 20.adaptSize, width: 20.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h, top: 3.v), child: Text("lbl_qatar_airways".tr, style: CustomTextStyles.labelLargeGray900_1))]), SizedBox(height: 15.v), Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_11_05_pm".tr, style: CustomTextStyles.titleSmallGray900_2), SizedBox(height: 7.v), CustomElevatedButton(height: 22.v, width: 42.h, text: "lbl_sin".tr, buttonStyle: CustomButtonStyles.fillGrayTL6, buttonTextStyle: CustomTextStyles.labelMediumPlusJakartaSans)]), CustomImageView(imagePath: ImageConstant.imgSettingsBlueGray100, height: 6.v, margin: EdgeInsets.only(left: 26.h, top: 18.v, bottom: 22.v)), CustomImageView(imagePath: ImageConstant.imgAirplaneBlueGray30001, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(left: 4.h, top: 9.v, bottom: 13.v)), CustomImageView(imagePath: ImageConstant.imgBarcode, height: 6.v, margin: EdgeInsets.only(left: 4.h, top: 18.v, bottom: 22.v)), Padding(padding: EdgeInsets.only(left: 21.h), child: Column(children: [Text("lbl_10_30_am".tr, style: CustomTextStyles.titleSmallGray900_2), SizedBox(height: 7.v), CustomElevatedButton(height: 22.v, width: 44.h, text: "lbl_lhr".tr, buttonStyle: CustomButtonStyles.fillGrayTL6, buttonTextStyle: CustomTextStyles.labelMediumPlusJakartaSans, alignment: Alignment.centerRight)]))])])); } 
/// Section Widget
Widget _buildList() { return Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 16.v);}, itemCount: controller.flightBookingTravelAddOnModelObj.value.list14ItemList.value.length, itemBuilder: (context, index) {List14ItemModel model = controller.flightBookingTravelAddOnModelObj.value.list14ItemList.value[index]; return List14ItemWidget(model);})); } 
/// Section Widget
Widget _buildHeader() { return Padding(padding: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 38.v), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.symmetric(vertical: 5.v), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_total_add_ons".tr, style: theme.textTheme.labelLarge), Padding(padding: EdgeInsets.only(top: 6.v), child: Text("lbl_8_00".tr, style: theme.textTheme.titleLarge))])), CustomElevatedButton(width: 159.h, text: "lbl_save".tr)])); } 

/// Navigates to the previous screen.
onTapClose() { Get.back(); } 
 }
