import 'package:trip_tailor/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:trip_tailor/core/app_export.dart';import 'controller/flight_payment_detail_order_controller.dart';
// ignore_for_file: must_be_immutable
class FlightPaymentDetailOrderBottomsheet extends StatelessWidget {FlightPaymentDetailOrderBottomsheet(this.controller, {Key? key}) : super(key: key);

FlightPaymentDetailOrderController controller;

@override Widget build(BuildContext context) { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 16.v), decoration: AppDecoration.fillOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.customBorderTL35), child: Column(mainAxisSize: MainAxisSize.min, children: [Container(height: 8.v, width: 40.h, decoration: BoxDecoration(color: appTheme.gray100, borderRadius: BorderRadius.circular(4.h))), SizedBox(height: 18.v), _buildFrame(), SizedBox(height: 18.v), Divider(), SizedBox(height: 22.v), _buildHeader(), SizedBox(height: 29.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_passenger".tr, style: theme.textTheme.titleMedium)), SizedBox(height: 16.v), _buildDetailGuest(), SizedBox(height: 49.v)])); } 
/// Section Widget
Widget _buildFrame() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_order_detail".tr, style: CustomTextStyles.titleMedium18_1), CustomImageView(imagePath: ImageConstant.imgCloseGray600, height: 20.adaptSize, width: 20.adaptSize, onTap: () {onTapImgClose();})]); } 
/// Section Widget
Widget _buildHeader() { return Container(width: 327.h, padding: EdgeInsets.all(15.h), decoration: AppDecoration.outlineBluegray100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgAirplanePrimary24x24, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(bottom: 15.v)), Padding(padding: EdgeInsets.only(left: 12.h, top: 5.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_11_05_pm_singapore".tr, style: CustomTextStyles.titleSmallGray900), SizedBox(height: 5.v), Text("lbl_changi_airport".tr, style: theme.textTheme.labelMedium)]))]), SizedBox(height: 16.v), Align(alignment: Alignment.centerRight, child: Container(margin: EdgeInsets.only(left: 36.h), padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 10.v), decoration: AppDecoration.fillGray10001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.end, crossAxisAlignment: CrossAxisAlignment.start, mainAxisSize: MainAxisSize.min, children: [Padding(padding: EdgeInsets.only(bottom: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [Padding(padding: EdgeInsets.only(top: 3.v), child: Text("lbl_qatar_airways".tr, style: CustomTextStyles.labelLargeGray900)), CustomImageView(imagePath: ImageConstant.imgQatarAirwaysSvg, height: 18.adaptSize, width: 18.adaptSize, margin: EdgeInsets.only(left: 8.h))]), SizedBox(height: 6.v), SizedBox(width: 156.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_friday_26_aug".tr, style: theme.textTheme.labelMedium), Container(height: 4.adaptSize, width: 4.adaptSize, margin: EdgeInsets.only(top: 2.v, bottom: 5.v), decoration: BoxDecoration(color: appTheme.blueGray100, borderRadius: BorderRadius.circular(2.h))), Text("lbl_economy_light".tr, style: theme.textTheme.labelMedium)]))])), Padding(padding: EdgeInsets.only(left: 31.h, top: 2.v, bottom: 22.v), child: Text("lbl_19h_25m".tr, style: CustomTextStyles.labelLargeBold))]))), SizedBox(height: 16.v), Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgAirplaneRedA100, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(bottom: 15.v)), Padding(padding: EdgeInsets.only(left: 12.h, top: 3.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_10_30_am_london".tr, style: CustomTextStyles.titleSmallGray900), SizedBox(height: 7.v), Text("lbl_heatrow_airport".tr, style: theme.textTheme.labelMedium)]))])])); } 
/// Section Widget
Widget _buildDetailGuest() { return Container(padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 16.v), decoration: AppDecoration.outlineGray200.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 4.v, bottom: 1.v), child: Text("msg_francene_vandyne".tr, style: CustomTextStyles.titleSmallGray900_2)), CustomElevatedButton(height: 22.v, width: 52.h, text: "lbl_adult".tr, buttonStyle: CustomButtonStyles.fillGrayTL6, buttonTextStyle: CustomTextStyles.labelMediumPlusJakartaSans)]), SizedBox(height: 17.v), Divider(), SizedBox(height: 17.v), Padding(padding: EdgeInsets.only(right: 34.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgBag, height: 16.adaptSize, width: 16.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("lbl_baggage_20_kg2".tr, style: theme.textTheme.labelLarge)), CustomImageView(imagePath: ImageConstant.imgTrophyBlueGray30001, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(left: 27.h)), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("msg_extra_protections".tr, style: theme.textTheme.labelLarge))]))])); } 

/// Navigates to the previous screen.
onTapImgClose() { Get.back(); } 
 }
