import 'package:trip_tailor/widgets/app_bar/custom_app_bar.dart';import 'package:trip_tailor/widgets/app_bar/appbar_leading_image.dart';import 'package:trip_tailor/widgets/app_bar/appbar_subtitle_two.dart';import 'package:trip_tailor/widgets/app_bar/appbar_trailing_image.dart';import 'widgets/list17_item_widget.dart';import 'models/list17_item_model.dart';import 'widgets/admissionmuseum_item_widget.dart';import 'models/admissionmuseum_item_model.dart';import 'package:flutter/material.dart';import 'package:trip_tailor/core/app_export.dart';import 'controller/attaraction_all_controller.dart';class AttaractionAllScreen extends GetWidget<AttaractionAllController> {const AttaractionAllScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [_buildTopBar(), Column(children: [SizedBox(height: 68.v), _buildTab(), SizedBox(height: 27.v), _buildTitle(), SizedBox(height: 15.v), _buildList(), SizedBox(height: 28.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Text("msg_recommendation_for".tr, style: CustomTextStyles.titleMedium18))), SizedBox(height: 15.v), _buildAdmissionMuseum()])])))); } 
/// Section Widget
Widget _buildTopBar() { return Container(decoration: AppDecoration.fillPrimary, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, top: 16.v, bottom: 16.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleTwo(text: "lbl_attractions".tr), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgRewindOnprimarycontainer, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 16.v))], styleType: Style.bgOutline_2), SizedBox(height: 12.v), Padding(padding: EdgeInsets.only(left: 24.h, right: 60.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgMapPinAmber200, height: 20.adaptSize, width: 20.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h, top: 3.v, bottom: 3.v), child: Text("lbl_where_next".tr, style: CustomTextStyles.titleSmallCyanA100)), Spacer(), SizedBox(height: 24.v, child: VerticalDivider(width: 1.h, thickness: 1.v, color: appTheme.cyanA10001)), CustomImageView(imagePath: ImageConstant.imgCalendarAmber200, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(left: 15.h)), Padding(padding: EdgeInsets.only(left: 8.h, top: 3.v, bottom: 3.v), child: Text("lbl_select_dates".tr, style: CustomTextStyles.titleSmallCyanA100))])), SizedBox(height: 12.v)])); } 
/// Section Widget
Widget _buildTab() { return Padding(padding: EdgeInsets.only(left: 24.h, right: 10.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(width: 52.h, padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 11.v), decoration: AppDecoration.fillLightBlue.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Text("lbl_all".tr, style: CustomTextStyles.titleSmallPrimaryBold)), Container(width: 112.h, margin: EdgeInsets.only(left: 12.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 10.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Text("lbl_water_parks".tr, style: theme.textTheme.titleSmall)), Container(width: 153.h, margin: EdgeInsets.only(left: 12.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 10.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Text("lbl_amusement_parks".tr, style: theme.textTheme.titleSmall))])); } 
/// Section Widget
Widget _buildTitle() { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("msg_popular_this_week".tr, style: CustomTextStyles.titleMedium18), Padding(padding: EdgeInsets.only(bottom: 4.v), child: Text("lbl_view_more".tr, style: CustomTextStyles.titleSmallPrimary))])); } 
/// Section Widget
Widget _buildList() { return Align(alignment: Alignment.centerRight, child: SizedBox(height: 249.v, child: Obx(() => ListView.separated(padding: EdgeInsets.only(left: 24.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 20.h);}, itemCount: controller.attaractionAllModelObj.value.list17ItemList.value.length, itemBuilder: (context, index) {List17ItemModel model = controller.attaractionAllModelObj.value.list17ItemList.value[index]; return List17ItemWidget(model);})))); } 
/// Section Widget
Widget _buildAdmissionMuseum() { return Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 20.v);}, itemCount: controller.attaractionAllModelObj.value.admissionmuseumItemList.value.length, itemBuilder: (context, index) {AdmissionmuseumItemModel model = controller.attaractionAllModelObj.value.admissionmuseumItemList.value[index]; return AdmissionmuseumItemWidget(model);})); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
