import 'package:trip_tailor/widgets/app_bar/custom_app_bar.dart';import 'package:trip_tailor/widgets/app_bar/appbar_leading_image.dart';import 'package:trip_tailor/widgets/app_bar/appbar_subtitle_one.dart';import 'package:trip_tailor/presentation/flight_form_multi_city_page/flight_form_multi_city_page.dart';import 'package:trip_tailor/presentation/flight_form_round_trip_page/flight_form_round_trip_page.dart';import 'package:flutter/material.dart';import 'package:trip_tailor/core/app_export.dart';import 'controller/flight_form_one_way_tab_container_controller.dart';class FlightFormOneWayTabContainerScreen extends GetWidget<FlightFormOneWayTabContainerController> {const FlightFormOneWayTabContainerScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [_buildFiftySix(), Expanded(child: SizedBox(height: 652.v, child: TabBarView(controller: controller.tabviewController, children: [FlightFormMultiCityPage(), FlightFormRoundTripPage()])))])))); } 
/// Section Widget
Widget _buildFiftySix() { return Container(padding: EdgeInsets.symmetric(vertical: 64.v), decoration: AppDecoration.fillPrimary, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomAppBar(height: 25.v, leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, bottom: 1.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleOne(text: "lbl_flight".tr)), SizedBox(height: 31.v), Container(height: 40.v, width: 199.h, margin: EdgeInsets.only(left: 24.h), child: TabBar(controller: controller.tabviewController, labelPadding: EdgeInsets.zero, labelColor: appTheme.cyanA100, labelStyle: TextStyle(fontSize: 14.fSize, fontFamily: 'Urbanist', fontWeight: FontWeight.w500), unselectedLabelColor: theme.colorScheme.onPrimaryContainer.withOpacity(1), unselectedLabelStyle: TextStyle(fontSize: 14.fSize, fontFamily: 'Urbanist', fontWeight: FontWeight.w700), indicator: BoxDecoration(borderRadius: BorderRadius.circular(12.h), border: Border.all(color: appTheme.cyanA10001, width: 1.h)), tabs: [Tab(child: Text("lbl_one_way".tr)), Tab(child: Text("lbl_multi_city".tr))])), SizedBox(height: 83.v)])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
