import 'package:trip_tailor/widgets/app_bar/custom_app_bar.dart';import 'package:trip_tailor/widgets/app_bar/appbar_leading_image.dart';import 'package:trip_tailor/widgets/app_bar/appbar_subtitle_one.dart';import 'package:trip_tailor/widgets/app_bar/appbar_trailing_image.dart';import 'package:trip_tailor/widgets/custom_text_form_field.dart';import 'models/button_item_model.dart';import '../hotel_form_screen/widgets/button_item_widget.dart';import 'widgets/stpeachtree_item_widget.dart';import 'models/stpeachtree_item_model.dart';import 'package:flutter/material.dart';import 'package:trip_tailor/core/app_export.dart';import 'controller/hotel_form_controller.dart';class HotelFormScreen extends GetWidget<HotelFormController> {const HotelFormScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(child: Column(children: [_buildForm(), SizedBox(height: 25.v), SizedBox(height: 528.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [_buildTripIdeas(), _buildNineteen(), _buildRecommendation()]))]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 307.v, leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, top: 64.v, bottom: 219.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleOne(text: "lbl_hotels".tr, margin: EdgeInsets.only(top: 65.v, bottom: 219.v)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgHeart, margin: EdgeInsets.fromLTRB(24.h, 64.v, 24.h, 219.v))], styleType: Style.bgFill); } 
/// Section Widget
Widget _buildForm() { return Container(margin: EdgeInsets.symmetric(horizontal: 24.h), padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 26.v), decoration: AppDecoration.outlineBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Column(mainAxisSize: MainAxisSize.min, children: [CustomTextFormField(controller: controller.searchController, hintText: "lbl_going_to".tr, hintStyle: theme.textTheme.titleSmall!, prefix: Container(margin: EdgeInsets.fromLTRB(12.h, 14.v, 10.h, 14.v), child: CustomImageView(imagePath: ImageConstant.imgMapPin, height: 20.adaptSize, width: 20.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 48.v), contentPadding: EdgeInsets.only(top: 15.v, right: 30.h, bottom: 15.v)), SizedBox(height: 16.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Container(margin: EdgeInsets.only(right: 5.h), padding: EdgeInsets.symmetric(horizontal: 11.h, vertical: 13.v), decoration: AppDecoration.outlineGray200.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgThumbsUpGray6001, height: 20.adaptSize, width: 20.adaptSize), Padding(padding: EdgeInsets.only(left: 10.h), child: Text("lbl_check_in".tr, style: theme.textTheme.titleSmall))]))), Expanded(child: Padding(padding: EdgeInsets.only(left: 6.h), child: CustomTextFormField(controller: controller.nightCounterController, hintText: "lbl_1_night".tr, hintStyle: CustomTextStyles.titleSmallGray900, contentPadding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 15.v))))]), SizedBox(height: 16.v), CustomTextFormField(controller: controller.searchController1, hintText: "lbl_room_guest".tr, hintStyle: theme.textTheme.titleSmall!, textInputAction: TextInputAction.done, prefix: Container(margin: EdgeInsets.fromLTRB(12.h, 14.v, 10.h, 14.v), child: CustomImageView(imagePath: ImageConstant.imgUsers, height: 20.adaptSize, width: 20.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 48.v), contentPadding: EdgeInsets.only(top: 15.v, right: 30.h, bottom: 15.v)), SizedBox(height: 24.v), Obx(() => Wrap(runSpacing: 12.v, spacing: 12.h, children: List<Widget>.generate(controller.hotelFormModelObj.value.buttonItemList.value.length, (index) {ButtonItemModel model = controller.hotelFormModelObj.value.buttonItemList.value[index]; return ButtonItemWidget(model);})))])); } 
/// Section Widget
Widget _buildTripIdeas() { return Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_ideas_for_your_next".tr, style: theme.textTheme.titleLarge), SizedBox(height: 16.v), Card(clipBehavior: Clip.antiAlias, elevation: 0, color: appTheme.gray10001, shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.roundedBorder20), child: Container(height: 180.v, width: 327.h, decoration: AppDecoration.fillGray10001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Stack(alignment: Alignment.bottomLeft, children: [CustomImageView(imagePath: ImageConstant.imgImage180x327, height: 180.v, radius: BorderRadius.circular(20.h), alignment: Alignment.center), Align(alignment: Alignment.bottomLeft, child: Padding(padding: EdgeInsets.only(left: 16.h, right: 89.h, bottom: 16.v), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_awaken_your_travel".tr, style: CustomTextStyles.titleMediumOnPrimaryContainer18), SizedBox(height: 2.v), Text("msg_experience_the_world".tr, style: CustomTextStyles.labelLargeOnPrimaryContainer)])))])))]))); } 
/// Section Widget
Widget _buildNineteen() { return Align(alignment: Alignment.bottomCenter, child: Container(margin: EdgeInsets.only(bottom: 170.v), padding: EdgeInsets.symmetric(horizontal: 134.h, vertical: 8.v), decoration: AppDecoration.gradientOnPrimaryContainerToOnPrimaryContainer, child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 34.v), Container(padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 11.v), decoration: AppDecoration.outlineGray900.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgMail, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(top: 4.v), child: Text("lbl_map".tr, style: CustomTextStyles.titleMediumOnPrimaryContainer))]))]))); } 
/// Section Widget
Widget _buildRecommendation() { return Align(alignment: Alignment.topRight, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(right: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_choice_for_you2".tr, style: CustomTextStyles.titleMedium18), Text("lbl_view_more".tr, style: CustomTextStyles.titleMediumPrimaryMedium)])), SizedBox(height: 18.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Expanded(child: Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 1.v);}, itemCount: controller.hotelFormModelObj.value.stpeachtreeItemList.value.length, itemBuilder: (context, index) {StpeachtreeItemModel model = controller.hotelFormModelObj.value.stpeachtreeItemList.value[index]; return StpeachtreeItemWidget(model);}))), Card(clipBehavior: Clip.antiAlias, elevation: 0, margin: EdgeInsets.all(0), shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.roundedBorder20), child: Container(height: 240.v, width: 200.h, decoration: AppDecoration.gradientGrayToGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder20), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgImage4, width: 200.h, radius: BorderRadius.circular(20.h), alignment: Alignment.center), Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgFavoriteGray900, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.centerRight), SizedBox(height: 139.v), Text("msg_quenn_anne_beach".tr, style: CustomTextStyles.titleMediumOnPrimaryContainer), SizedBox(height: 7.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgMapPinOnprimarycontainer, height: 14.adaptSize, width: 14.adaptSize), Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_hawaii".tr, style: CustomTextStyles.labelLargeOnPrimaryContainer))])])))])))])]))); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
