import 'package:trip_tailor/widgets/app_bar/custom_app_bar.dart';import 'package:trip_tailor/widgets/app_bar/appbar_leading_image.dart';import 'package:trip_tailor/widgets/app_bar/appbar_subtitle.dart';import 'package:trip_tailor/widgets/app_bar/appbar_trailing_image.dart';import 'package:trip_tailor/presentation/my_booking_list_page/my_booking_list_page.dart';import 'package:trip_tailor/presentation/my_booking_empty_page/my_booking_empty_page.dart';import 'package:flutter/material.dart';import 'package:trip_tailor/core/app_export.dart';import 'controller/my_booking_list_tab_container_controller.dart';class MyBookingListTabContainerScreen extends GetWidget<MyBookingListTabContainerController> {const MyBookingListTabContainerScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 11.v), _buildTabview(), SizedBox(height: 651.v, child: TabBarView(controller: controller.tabviewController, children: [MyBookingListPage(), MyBookingEmptyPage()]))])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowRight, margin: EdgeInsets.only(left: 24.h, top: 15.v, bottom: 16.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitle(text: "lbl_booking".tr), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgTelevision, margin: EdgeInsets.fromLTRB(24.h, 15.v, 24.h, 16.v))]); } 
/// Section Widget
Widget _buildTabview() { return Container(height: 44.v, width: 327.h, decoration: BoxDecoration(color: appTheme.gray10001, borderRadius: BorderRadius.circular(10.h)), child: TabBar(controller: controller.tabviewController, labelPadding: EdgeInsets.zero, labelColor: appTheme.gray900, labelStyle: TextStyle(fontSize: 12.fSize, fontFamily: 'Urbanist', fontWeight: FontWeight.w700), unselectedLabelColor: appTheme.gray600, unselectedLabelStyle: TextStyle(fontSize: 12.fSize, fontFamily: 'Urbanist', fontWeight: FontWeight.w500), indicatorPadding: EdgeInsets.all(4.0.h), indicator: BoxDecoration(color: theme.colorScheme.onPrimaryContainer.withOpacity(1), borderRadius: BorderRadius.circular(8.h)), tabs: [Tab(child: Text("lbl_past_order".tr)), Tab(child: Text("lbl_past_refund".tr))])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
