import 'package:trip_tailor/widgets/custom_search_view.dart';import 'package:flutter/material.dart';import 'package:trip_tailor/core/app_export.dart';import 'controller/hotel_list_controller.dart';class HotelListScreen extends GetWidget<HotelListController> {const HotelListScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 56.v), Expanded(child: SingleChildScrollView(child: Column(children: [_buildAppbar(), SizedBox(height: 29.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Text("msg_1_987_best_stays".tr, style: theme.textTheme.titleMedium))), SizedBox(height: 16.v), SizedBox(height: 838.v, width: double.maxFinite, child: Stack(alignment: Alignment.center, children: [_buildEighteen(), Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [_buildCard(img: ImageConstant.imgImg170x327), SizedBox(height: 15.v), Text("msg_commerce_casino".tr, style: theme.textTheme.titleMedium), SizedBox(height: 10.v), _buildLocation(label: "lbl_los_angeles".tr), SizedBox(height: 10.v), _buildFooter(price: "lbl_150_night".tr, label: "msg_4_9_825_reviews".tr), SizedBox(height: 21.v), _buildCard(img: ImageConstant.imgImg14), SizedBox(height: 15.v), Text("msg_commerce_casino".tr, style: theme.textTheme.titleMedium), SizedBox(height: 10.v), _buildLocation(label: "lbl_los_angeles".tr), SizedBox(height: 10.v), _buildFooter(price: "lbl_150_night".tr, label: "msg_4_9_825_reviews".tr), SizedBox(height: 21.v), _buildCard4()])))]))])))])))); } 
/// Section Widget
Widget _buildAppbar() { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.symmetric(vertical: 12.v), onTap: () {onTapImgArrowLeft();}), Expanded(child: Padding(padding: EdgeInsets.only(left: 16.h), child: CustomSearchView(controller: controller.searchController, hintText: "lbl_los_angeles".tr, hintStyle: CustomTextStyles.titleSmallGray900_2, contentPadding: EdgeInsets.symmetric(vertical: 15.v), borderDecoration: SearchViewStyleHelper.outlineGrayTL121)))])); } 
/// Section Widget
Widget _buildEighteen() { return Align(alignment: Alignment.bottomCenter, child: Container(margin: EdgeInsets.only(bottom: 196.v), padding: EdgeInsets.symmetric(horizontal: 102.h, vertical: 8.v), decoration: AppDecoration.gradientOnPrimaryContainerToOnPrimaryContainer1, child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 34.v), Container(padding: EdgeInsets.symmetric(vertical: 11.v), decoration: AppDecoration.outlineGray900.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Row(mainAxisAlignment: MainAxisAlignment.spaceEvenly, children: [CustomImageView(imagePath: ImageConstant.imgMail, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 2.v)), Padding(padding: EdgeInsets.only(top: 4.v), child: Text("lbl_map".tr, style: CustomTextStyles.titleMediumOnPrimaryContainer)), SizedBox(height: 24.v, child: VerticalDivider(width: 1.h, thickness: 1.v, color: appTheme.blueGray800)), CustomImageView(imagePath: ImageConstant.imgShare, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 2.v)), Padding(padding: EdgeInsets.only(top: 2.v), child: Text("lbl_sort".tr, style: CustomTextStyles.titleMediumOnPrimaryContainer))]))]))); } 
/// Section Widget
Widget _buildCard4() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildCard(img: ImageConstant.imgImg15), SizedBox(height: 12.v), Text("msg_loews_hollywood".tr, style: theme.textTheme.titleMedium), SizedBox(height: 4.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgMapPin, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.symmetric(vertical: 4.v)), Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_west_hollywood".tr, style: theme.textTheme.titleSmall))]), SizedBox(height: 4.v), _buildFooter(price: "lbl_235_night".tr, label: "msg_4_9_825_reviews".tr)]); } 
/// Common widget
Widget _buildCard({required String img}) { return Card(clipBehavior: Clip.antiAlias, elevation: 0, margin: EdgeInsets.all(0), color: appTheme.gray10001, shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.roundedBorder16), child: Container(height: 170.v, width: 327.h, decoration: AppDecoration.fillGray10001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Stack(alignment: Alignment.topRight, children: [CustomImageView(imagePath: img, height: 170.v, radius: BorderRadius.circular(16.h), alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgFavoriteGray900, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.topRight, margin: EdgeInsets.only(top: 16.v, right: 16.h))]))); } 
/// Common widget
Widget _buildLocation({required String label}) { return Row(children: [CustomImageView(imagePath: ImageConstant.imgMapPin, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(bottom: 2.v)), Padding(padding: EdgeInsets.only(left: 6.h), child: Text(label, style: theme.textTheme.titleSmall!.copyWith(color: appTheme.gray600)))]); } 
/// Common widget
Widget _buildFooter({required String price, required String label, }) { return Row(crossAxisAlignment: CrossAxisAlignment.start, children: [RichText(text: TextSpan(children: [TextSpan(text: "lbl_150".tr, style: CustomTextStyles.titleMediumff111827_1), TextSpan(text: "lbl_night".tr, style: CustomTextStyles.bodySmallff6b7280)]), textAlign: TextAlign.left), Spacer(), CustomImageView(imagePath: ImageConstant.imgStarGray600, height: 14.adaptSize, width: 14.adaptSize, margin: EdgeInsets.only(bottom: 4.v)), Padding(padding: EdgeInsets.only(left: 4.h, bottom: 2.v), child: Text(label, style: theme.textTheme.titleSmall!.copyWith(color: appTheme.gray600)))]); } 

/// Navigates to the previous screen.
onTapImgArrowLeft() { Get.back(); } 
 }
