import 'package:trip_tailor/widgets/app_bar/custom_app_bar.dart';import 'package:trip_tailor/widgets/app_bar/appbar_leading_image.dart';import 'package:trip_tailor/widgets/app_bar/appbar_trailing_image.dart';import 'package:trip_tailor/presentation/attaraction_detail_description_page/attaraction_detail_description_page.dart';import 'package:trip_tailor/presentation/attaraction_detail_photos_page/attaraction_detail_photos_page.dart';import 'package:trip_tailor/presentation/attaraction_detail_packages_page/attaraction_detail_packages_page.dart';import 'package:trip_tailor/presentation/attaraction_detail_reviews_page/attaraction_detail_reviews_page.dart';import 'package:flutter/material.dart';import 'package:trip_tailor/core/app_export.dart';import 'controller/attaraction_detail_description_tab_container_controller.dart';class AttaractionDetailDescriptionTabContainerScreen extends GetWidget<AttaractionDetailDescriptionTabContainerController> {const AttaractionDetailDescriptionTabContainerScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 24.v), child: Column(children: [_buildTabview(), SizedBox(height: 640.v, child: TabBarView(controller: controller.tabviewController, children: [AttaractionDetailDescriptionPage(), AttaractionDetailPhotosPage(), AttaractionDetailPhotosPage(), AttaractionDetailPackagesPage(), AttaractionDetailReviewsPage()]))]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 108.v, leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowLeft();}), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgTwitter, margin: EdgeInsets.only(left: 24.h, top: 20.v, right: 20.h)), AppbarTrailingImage(imagePath: ImageConstant.imgHeartOnprimarycontainer, margin: EdgeInsets.only(left: 16.h, top: 20.v, right: 44.h))], styleType: Style.bgOutline_1); } 
/// Section Widget
Widget _buildTabview() { return SizedBox(height: 40.v, width: 351.h, child: TabBar(controller: controller.tabviewController, isScrollable: true, labelColor: theme.colorScheme.primary, labelStyle: TextStyle(fontSize: 14.fSize, fontFamily: 'Urbanist', fontWeight: FontWeight.w700), unselectedLabelColor: appTheme.gray600, unselectedLabelStyle: TextStyle(fontSize: 14.fSize, fontFamily: 'Urbanist', fontWeight: FontWeight.w500), indicator: BoxDecoration(color: appTheme.lightBlue50, borderRadius: BorderRadius.circular(10.h)), tabs: [Tab(child: Text("lbl_overview".tr)), Tab(child: Text("lbl_gallery".tr)), Tab(child: Text("lbl_location".tr)), Tab(child: Text("lbl_packages".tr)), Tab(child: Text("lbl_reviews".tr))])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
