import 'package:trip_tailor/widgets/app_bar/custom_app_bar.dart';import 'package:trip_tailor/widgets/app_bar/appbar_leading_image.dart';import 'package:trip_tailor/widgets/app_bar/appbar_subtitle_one.dart';import 'package:trip_tailor/widgets/app_bar/appbar_trailing_image.dart';import 'package:trip_tailor/widgets/custom_icon_button.dart';import 'package:trip_tailor/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:trip_tailor/core/app_export.dart';import 'controller/flight_booking_extra_protection_controller.dart';class FlightBookingExtraProtectionScreen extends GetWidget<FlightBookingExtraProtectionController> {const FlightBookingExtraProtectionScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: Container(height: SizeUtils.height, width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 38.v), child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.center, child: Column(mainAxisSize: MainAxisSize.min, children: [_buildAppBar(), SizedBox(height: 29.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 23.h), child: Text("msg_extra_protections".tr, style: theme.textTheme.titleMedium))), SizedBox(height: 16.v), _buildExtraProtection1(), SizedBox(height: 15.v), Padding(padding: EdgeInsets.symmetric(horizontal: 23.h), child: _buildExtraProtection(thumbsUp: ImageConstant.imgHome, label: "msg_full_trip_protections".tr, description: "msg_covering_trip_accident".tr, label1: "lbl_see_details".tr)), SizedBox(height: 15.v), Padding(padding: EdgeInsets.symmetric(horizontal: 23.h), child: _buildExtraProtection(thumbsUp: ImageConstant.imgThumbsUpBlueGray3000124x24, label: "msg_baggage_insurance".tr, description: "msg_covering_trip_accident".tr, label1: "lbl_see_details".tr)), SizedBox(height: 24.v), _buildGuarantee()])), _buildBottomBar()])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 64.v, leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 20.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleOne(text: "lbl_booking".tr), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgDotsVerticalOnprimarycontainer, margin: EdgeInsets.symmetric(horizontal: 24.h, vertical: 20.v))], styleType: Style.bgOutline_1); } 
/// Section Widget
Widget _buildExtraProtection1() { return Container(margin: EdgeInsets.symmetric(horizontal: 23.h), padding: EdgeInsets.all(15.h), decoration: AppDecoration.outlinePrimary3.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgTrophyBlueGray30001, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(bottom: 96.v)), Expanded(child: Padding(padding: EdgeInsets.only(left: 12.h, bottom: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 3.v), child: Text("msg_free_protections".tr, style: CustomTextStyles.titleSmallGray900)), CustomIconButton(height: 20.adaptSize, width: 20.adaptSize, padding: EdgeInsets.all(3.h), decoration: IconButtonStyleHelper.fillPrimary, child: CustomImageView(imagePath: ImageConstant.imgArrowLeft))]), SizedBox(height: 11.v), Container(width: 241.h, margin: EdgeInsets.only(right: 17.h), child: Text("msg_covering_trip_accident".tr, maxLines: 3, overflow: TextOverflow.ellipsis, style: theme.textTheme.labelLarge!.copyWith(height: 1.70))), SizedBox(height: 6.v), Text("lbl_see_details".tr, style: CustomTextStyles.labelLargePrimaryBold)])))])); } 
/// Section Widget
Widget _buildGuarantee() { return Container(margin: EdgeInsets.symmetric(horizontal: 23.h), padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 10.v), decoration: AppDecoration.fillGray10001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Row(mainAxisAlignment: MainAxisAlignment.center, mainAxisSize: MainAxisSize.min, children: [Padding(padding: EdgeInsets.symmetric(vertical: 3.v), child: CustomIconButton(height: 48.adaptSize, width: 48.adaptSize, padding: EdgeInsets.all(12.h), decoration: IconButtonStyleHelper.fillOnPrimaryContainer, child: CustomImageView(imagePath: ImageConstant.imgCloseBlueGray80001))), Expanded(child: Padding(padding: EdgeInsets.only(left: 12.h, top: 3.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_lowest_price_guarentee".tr, style: CustomTextStyles.labelLargeGray900), SizedBox(height: 3.v), SizedBox(width: 242.h, child: Text("msg_get_compensated".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.labelMedium!.copyWith(height: 1.60)))])))])); } 
/// Section Widget
Widget _buildBottomBar() { return Align(alignment: Alignment.bottomCenter, child: Container(width: double.maxFinite, margin: EdgeInsets.only(top: 668.v), padding: EdgeInsets.symmetric(horizontal: 24.h), decoration: AppDecoration.outlineGrayF, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(top: 17.v, bottom: 4.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [Text("lbl_744_00".tr, style: theme.textTheme.titleLarge), CustomImageView(imagePath: ImageConstant.imgArrowDownBlueGray30001, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(left: 4.h, top: 4.v, bottom: 4.v))]), SizedBox(height: 7.v), RichText(text: TextSpan(children: [TextSpan(text: "lbl_get".tr, style: CustomTextStyles.labelLargeff6b7280), TextSpan(text: "lbl_10_000_points".tr, style: CustomTextStyles.labelLargee816d4e9)]), textAlign: TextAlign.left)])), CustomElevatedButton(width: 159.h, text: "lbl_continue".tr, margin: EdgeInsets.only(top: 12.v))]))); } 
/// Common widget
Widget _buildExtraProtection({required String thumbsUp, required String label, required String description, required String label1, }) { return Container(padding: EdgeInsets.all(15.h), decoration: AppDecoration.outlineBluegray100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: thumbsUp, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(bottom: 96.v)), Expanded(child: Padding(padding: EdgeInsets.only(left: 12.h, bottom: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 3.v), child: Text(label, style: CustomTextStyles.titleSmallGray900.copyWith(color: appTheme.gray900))), CustomImageView(imagePath: ImageConstant.imgThumbsUpBlueGray100, height: 20.adaptSize, width: 20.adaptSize)]), SizedBox(height: 11.v), Container(width: 241.h, margin: EdgeInsets.only(right: 17.h), child: Text(description, maxLines: 3, overflow: TextOverflow.ellipsis, style: theme.textTheme.labelLarge!.copyWith(color: appTheme.gray600, height: 1.70))), SizedBox(height: 6.v), Text(label1, style: CustomTextStyles.labelLargePrimaryBold.copyWith(color: theme.colorScheme.primary))])))])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
