import 'package:trip_tailor/widgets/app_bar/custom_app_bar.dart';import 'package:trip_tailor/widgets/app_bar/appbar_leading_image.dart';import 'package:trip_tailor/widgets/custom_icon_button.dart';import 'package:trip_tailor/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:trip_tailor/core/app_export.dart';import 'controller/success_state_new_password_controller.dart';class SuccessStateNewPasswordScreen extends GetWidget<SuccessStateNewPasswordController> {const SuccessStateNewPasswordScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.only(top: 80.v), child: Column(children: [Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(top: 15.v, bottom: 9.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Align(alignment: Alignment.centerRight, child: Container(height: 4.adaptSize, width: 4.adaptSize, decoration: BoxDecoration(color: appTheme.yellow400, borderRadius: BorderRadius.circular(2.h)))), SizedBox(height: 88.v), Container(height: 4.adaptSize, width: 4.adaptSize, decoration: BoxDecoration(color: appTheme.redA100, borderRadius: BorderRadius.circular(2.h)))])), Container(height: 120.v, width: 139.h, margin: EdgeInsets.only(left: 9.h), child: Stack(alignment: Alignment.topRight, children: [Align(alignment: Alignment.centerLeft, child: Container(margin: EdgeInsets.only(right: 19.h), decoration: AppDecoration.fillGray10001.copyWith(borderRadius: BorderRadiusStyle.circleBorder60), child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 9.v), Align(alignment: Alignment.centerRight, child: Container(height: 4.adaptSize, width: 4.adaptSize, decoration: BoxDecoration(color: appTheme.tealA400, borderRadius: BorderRadius.circular(2.h)))), SizedBox(height: 12.v), CustomImageView(imagePath: ImageConstant.imgCheckmarkOnprimarycontainer, width: 72.h)]))), Align(alignment: Alignment.topRight, child: Container(height: 7.adaptSize, width: 7.adaptSize, margin: EdgeInsets.only(top: 17.v, right: 6.h), decoration: BoxDecoration(color: appTheme.gray200, borderRadius: BorderRadius.circular(3.h)))), Align(alignment: Alignment.bottomRight, child: Container(margin: EdgeInsets.only(left: 52.h, top: 59.v, bottom: 17.v), padding: EdgeInsets.symmetric(horizontal: 7.h, vertical: 8.v), decoration: AppDecoration.outlineOnErrorContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.symmetric(vertical: 2.v), child: CustomIconButton(height: 22.adaptSize, width: 22.adaptSize, padding: EdgeInsets.all(3.h), decoration: IconButtonStyleHelper.fillGreenA, child: CustomImageView(imagePath: ImageConstant.imgCheck))), CustomImageView(imagePath: ImageConstant.imgThumbsUp, height: 26.v, margin: EdgeInsets.only(left: 6.h))])))]))]), SizedBox(height: 35.v), Text("msg_password_updated".tr, style: theme.textTheme.headlineSmall), SizedBox(height: 9.v), SizedBox(width: 227.h, child: Text("msg_your_password_has".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.titleMediumGray600Medium.copyWith(height: 1.65))), SizedBox(height: 5.v)])), bottomNavigationBar: _buildBackToLogin())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingImage(imagePath: ImageConstant.imgVector, margin: EdgeInsets.fromLTRB(33.h, 22.v, 336.h, 22.v), onTap: () {onTapVector();})); } 
/// Section Widget
Widget _buildBackToLogin() { return CustomElevatedButton(text: "lbl_back_to_login".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 42.v)); } 

/// Navigates to the previous screen.
onTapVector() { Get.back(); } 
 }
