import 'package:trip_tailor/widgets/app_bar/custom_app_bar.dart';import 'package:trip_tailor/widgets/app_bar/appbar_leading_image.dart';import 'package:trip_tailor/widgets/app_bar/appbar_subtitle_four.dart';import 'package:trip_tailor/widgets/app_bar/appbar_subtitle_nine.dart';import 'package:trip_tailor/widgets/app_bar/appbar_trailing_iconbutton_one.dart';import 'package:trip_tailor/widgets/custom_elevated_button.dart';import 'package:trip_tailor/widgets/custom_icon_button.dart';import 'package:trip_tailor/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';import 'package:trip_tailor/core/app_export.dart';import 'controller/flight_payment_controller.dart';class FlightPaymentScreen extends GetWidget<FlightPaymentController> {const FlightPaymentScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [_buildFifty(), Container(padding: EdgeInsets.all(24.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildCardBooking(), SizedBox(height: 28.v), _buildTitle(), SizedBox(height: 16.v), _buildPayment(), SizedBox(height: 21.v), Text("lbl_coupon".tr, style: theme.textTheme.titleMedium), SizedBox(height: 12.v), _buildInput(), SizedBox(height: 17.v), Text("msg_you_have_3_coupons".tr, style: CustomTextStyles.titleSmallBluegray30001), SizedBox(height: 5.v)]))])), bottomNavigationBar: _buildBottomBar())); } 
/// Section Widget
Widget _buildFifty() { return Container(padding: EdgeInsets.symmetric(vertical: 13.v), decoration: AppDecoration.fillPrimary, child: Column(children: [SizedBox(height: 46.v), CustomAppBar(height: 37.v, leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, top: 4.v, bottom: 8.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: Column(children: [AppbarSubtitleFour(text: "msg_continue_to_payment".tr), SizedBox(height: 5.v), AppbarSubtitleNine(text: "msg_booking_id_23456xx".tr, margin: EdgeInsets.symmetric(horizontal: 10.h))]), actions: [AppbarTrailingIconbuttonOne(imagePath: ImageConstant.imgProfileCyanA100, margin: EdgeInsets.fromLTRB(24.h, 4.v, 24.h, 8.v))]), SizedBox(height: 24.v), Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(width: 18.adaptSize, padding: EdgeInsets.symmetric(horizontal: 7.h, vertical: 1.v), decoration: AppDecoration.fillOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Text("lbl_1".tr, style: CustomTextStyles.labelLargePrimaryBold)), Padding(padding: EdgeInsets.only(left: 6.h), child: Text("lbl_select_method".tr, style: CustomTextStyles.labelLargeOnPrimaryContainerBold)), Container(height: 2.v, width: 16.h, margin: EdgeInsets.only(left: 8.h, top: 8.v, bottom: 8.v), decoration: BoxDecoration(color: theme.colorScheme.onPrimaryContainer.withOpacity(1), borderRadius: BorderRadius.circular(1.h))), Container(width: 18.adaptSize, margin: EdgeInsets.only(left: 8.h), padding: EdgeInsets.symmetric(horizontal: 5.h, vertical: 1.v), decoration: AppDecoration.outlineCyanA10001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Text("lbl_2".tr, style: CustomTextStyles.labelLargeCyanA10001)), Padding(padding: EdgeInsets.only(left: 6.h, top: 2.v), child: Text("lbl_payment".tr, style: CustomTextStyles.labelLargeCyanA100_1)), Container(height: 2.v, width: 16.h, margin: EdgeInsets.only(left: 8.h, top: 8.v, bottom: 8.v), decoration: BoxDecoration(color: appTheme.cyanA100, borderRadius: BorderRadius.circular(1.h))), Container(width: 18.adaptSize, margin: EdgeInsets.only(left: 8.h), padding: EdgeInsets.symmetric(horizontal: 5.h, vertical: 1.v), decoration: AppDecoration.outlineCyanA10001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Text("lbl_3".tr, style: CustomTextStyles.labelLargeCyanA10001)), Padding(padding: EdgeInsets.only(left: 6.h, top: 2.v), child: Text("lbl_complete".tr, style: CustomTextStyles.labelLargeCyanA100_1))]))])); } 
/// Section Widget
Widget _buildSIN() { return CustomElevatedButton(height: 22.v, width: 42.h, text: "lbl_sin".tr, buttonStyle: CustomButtonStyles.fillGrayTL6, buttonTextStyle: CustomTextStyles.labelMediumPlusJakartaSans); } 
/// Section Widget
Widget _buildLHR() { return CustomElevatedButton(height: 22.v, width: 44.h, text: "lbl_lhr".tr, buttonStyle: CustomButtonStyles.fillGrayTL6, buttonTextStyle: CustomTextStyles.labelMediumPlusJakartaSans, alignment: Alignment.centerRight); } 
/// Section Widget
Widget _buildOne() { return CustomElevatedButton(height: 22.v, width: 22.h, text: "lbl_01".tr, buttonStyle: CustomButtonStyles.fillLightBlue, buttonTextStyle: CustomTextStyles.labelMediumPrimary); } 
/// Section Widget
Widget _buildCardBooking() { return Container(padding: EdgeInsets.all(15.h), decoration: AppDecoration.outlineBluegray100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Column(mainAxisSize: MainAxisSize.min, children: [Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgQatarAirwaysSvg, height: 20.adaptSize, width: 20.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h, top: 3.v), child: Text("lbl_qatar_airways".tr, style: CustomTextStyles.labelLargeGray900_1)), Spacer(), Padding(padding: EdgeInsets.symmetric(vertical: 2.v), child: Text("lbl_see_details".tr, style: CustomTextStyles.labelLargePrimaryBold))]), SizedBox(height: 15.v), Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_11_05_pm".tr, style: CustomTextStyles.titleSmallGray900_2), SizedBox(height: 7.v), _buildSIN()]), CustomImageView(imagePath: ImageConstant.imgSettingsBlueGray100, height: 6.v, margin: EdgeInsets.only(left: 26.h, top: 18.v, bottom: 22.v)), CustomImageView(imagePath: ImageConstant.imgAirplaneBlueGray30001, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(left: 4.h, top: 9.v, bottom: 13.v)), CustomImageView(imagePath: ImageConstant.imgBarcode, height: 6.v, margin: EdgeInsets.only(left: 4.h, top: 18.v, bottom: 22.v)), Padding(padding: EdgeInsets.only(left: 21.h), child: Column(children: [Text("lbl_10_30_am".tr, style: CustomTextStyles.titleSmallGray900_2), SizedBox(height: 7.v), _buildLHR()]))]), SizedBox(height: 16.v), Divider(), SizedBox(height: 15.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(top: 4.v, bottom: 2.v), child: Text("msg_complete_your_payment".tr, style: CustomTextStyles.labelLargeGray900)), Spacer(), _buildOne(), CustomImageView(imagePath: ImageConstant.imgTitle, width: 2.h, margin: EdgeInsets.only(left: 6.h, top: 7.v, bottom: 7.v)), Container(width: 22.adaptSize, margin: EdgeInsets.only(left: 6.h), padding: EdgeInsets.symmetric(horizontal: 5.h, vertical: 4.v), decoration: AppDecoration.fillLightBlue.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Text("lbl_452".tr, style: CustomTextStyles.labelMediumPrimary)), CustomImageView(imagePath: ImageConstant.imgTitle, width: 2.h, margin: EdgeInsets.only(left: 6.h, top: 7.v, bottom: 7.v)), Container(width: 22.adaptSize, margin: EdgeInsets.only(left: 6.h), padding: EdgeInsets.all(4.h), decoration: AppDecoration.fillLightBlue.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Text("lbl_00".tr, style: CustomTextStyles.labelMediumPrimary))])])); } 
/// Section Widget
Widget _buildTitle() { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("msg_payment_information".tr, style: theme.textTheme.titleMedium), Text("lbl_change".tr, style: CustomTextStyles.titleSmallPrimaryBold)]); } 
/// Section Widget
Widget _buildPayment() { return Container(padding: EdgeInsets.all(15.h), decoration: AppDecoration.outlineBluegray1001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Row(children: [CustomIconButton(height: 48.adaptSize, width: 48.adaptSize, padding: EdgeInsets.all(11.h), decoration: IconButtonStyleHelper.fillGrayTL12, child: CustomImageView(imagePath: ImageConstant.imgSettingsLightBlue900)), Padding(padding: EdgeInsets.only(left: 16.h, top: 3.v, bottom: 2.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_citibank".tr, style: CustomTextStyles.titleSmallGray900), SizedBox(height: 9.v), Text("lbl_virtual_account".tr, style: theme.textTheme.labelLarge)]))])); } 
/// Section Widget
Widget _buildInput() { return CustomTextFormField(controller: controller.inputController, hintText: "lbl_coupon_code".tr, hintStyle: CustomTextStyles.bodyLargeBluegray30001, textInputAction: TextInputAction.done, prefix: Container(margin: EdgeInsets.fromLTRB(16.h, 18.v, 12.h, 18.v), child: CustomImageView(imagePath: ImageConstant.imgTelevision20x20, height: 20.adaptSize, width: 20.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 56.v), suffix: Padding(padding: EdgeInsets.fromLTRB(30.h, 18.v, 16.h, 17.v), child: Text("lbl_add".tr, style: TextStyle(color: Color(0XE816D4E9), fontSize: 16.fSize, fontFamily: 'Urbanist', fontWeight: FontWeight.w700))), suffixConstraints: BoxConstraints(maxHeight: 56.v), contentPadding: EdgeInsets.only(top: 18.v, right: 30.h, bottom: 18.v), borderDecoration: TextFormFieldStyleHelper.outlineBlueGrayTL16); } 
/// Section Widget
Widget _buildPayWithCitibank() { return CustomElevatedButton(width: 174.h, text: "msg_pay_with_citibank".tr); } 
/// Section Widget
Widget _buildBottomBar() { return Container(margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 38.v), decoration: AppDecoration.fillOnPrimaryContainer, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 5.v, bottom: 4.v), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [Text("lbl_744_00".tr, style: theme.textTheme.titleLarge), CustomImageView(imagePath: ImageConstant.imgArrowDownBlueGray30001, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(left: 4.h, top: 4.v, bottom: 4.v))]), Padding(padding: EdgeInsets.only(top: 7.v), child: RichText(text: TextSpan(children: [TextSpan(text: "lbl_get".tr, style: CustomTextStyles.labelLargeff6b7280), TextSpan(text: "lbl_10_000_points".tr, style: CustomTextStyles.labelLargee816d4e9)]), textAlign: TextAlign.left))])), _buildPayWithCitibank()])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
